### ISSUE TITLE
Сортировка грида ломается при добавлении коллекции

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#100]
После добавлении работы в еще одну коллекцию сортировка нарушается
![image](https://cloud.githubusercontent.com/assets/13114324/13199485/ae47962c-d837-11e5-9742-4860f72a36dc.png)

**Comment by Databoom** [comment]
Обнаружил, что она также ломается при добавлении строки или колонки (не заметил, когда)
![image](https://cloud.githubusercontent.com/assets/13114324/13258992/8b28f04c-da66-11e5-87ca-934575facd03.png)

**Comment by ixdu** [comment]
Подтверждаю, при изменении объекта, появлении у него новых свойств или новых элементов в массиве коллекций - почему-то неправильно отрабатывается order модификатор базой. Буду копать дальше:)

**Comment by ixdu** [comment]
В общем тут куча проблем была, часть из них решилась(на тестовом сервере, скоро будет на основном), возможно все. Ещё немного доработаю грид и возможно полностью исчезнут. На вскидку один из главных косяков был в том, что грид в принципе не работал с типами данных и сохранял всё как строки. При обновлении любой строки все его данные сохранялись как строки. Ну и тд.

**Comment by ixdu** [comment]
Пока больше воспроизвести не получается.

**Comment by ixdu** [comment]
Обнарушил баг, однако к добавлению к коллекции отношения не имеет, но база неадекватно сортирует, если в одном из объектов нету свойства по котором идёт сортировка.
