### ISSUE TITLE
Колонки перескакивают (воспроизвести не удалось)

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#102]
После действий с Add Column (я нажал add column, потом что-то думал, тыкал, не помню, в общем в результате раздумал добавлять колонку. После закрытия диалога колонка Collections перескочила в начало. 
![image](https://cloud.githubusercontent.com/assets/13114324/13199647/3435ecf8-d83c-11e5-9ff7-363701717d0d.png)

**Comment by ixdu** [comment]
Понаблюдаю. Сейчас, если добавления колонки не произошло то вообще ничего не происходит, возможно грид что-то сам делает в каких-то случаях.
