### ISSUE TITLE
Нет кнопки отмены редактирования в JSON View

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#103]
Если я нажимаю на "карандаш" - то я могу редактировать. При этом, есть кнопка "дискета". По ней я сохраняю результат. 

По смыслу, "карандаш" в режиме редактирования должен менять смысл на "отменить редактирование, выйти из режима редактирования без сохранения". Может быть, его иконку стоит заменить на перечеркнутый карандаш или что-то в этом роде. 

В любом случае, нет способа выйти из режима редактирования без сохранения.

**Comment by ixdu** [comment]
Добавил изменение иконки при редактировании. На основном появится вместе с обновлением json редактора.
