### ISSUE TITLE
Генерация ID

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#104]
В Grid View если нажать add row автоматически генерируется ID для нового объекта. 
В JSON view ID не генерится. при создании нового объекта. Это в принципе, нормально, в JSON можно руками скопировать объект и модифицировать его атрибуты, чтобы получился новый объект. Но одна загвоздка - id тоже копируется, а он должен быть уникальным. Стало быть я должен как-то сделать уникальный ID

Может быть стоит в JSON view сделать кнопку генерации ID, которая бы генерила ID в текст бокс либо прямо в clipboard?

**Comment by ixdu** [comment]
id генерируется для любого объекта, у которого его нет. Другое дело, что если нужно сразу создать множество объектов с ссылками на друг друга по id, тогда нужно при редактировании иметь эти id в наличии.

id генерируется только вместе с объектом, да, можно сделать чтобы генерировался пустой объект, который можно скопипастить, сделаю .

**Comment by Databoom** [comment]
В JSON желательно все оставить максимально ручным, поэтому не надо в нем генерировать пустой объект. Только кнопку для генерации ID. Лучше предварительно со Славой обсудить.

**Comment by ixdu** [comment]
Добавил кнопку в режим редактирования, генерирует id тем же методом что и для всех остальных объектов и отображает его в инпуте во всплывающем диалоге.

**Comment by Databoom** [comment]
Прекрасно сделано, можно было бы добавить сюда кроме OK еще кнопку "copy to clipboard"?

**Comment by ixdu** [comment]
Сделано.
