### ISSUE TITLE
Нет доступа к базе по URL

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#105]
Девушка зарегистрированная у нас
-------------------
Account ID: t258
Database ID: b258
Root login: tais_kat@list.ru
Root password: Dtyz2006
Database: https://t258.databoom.space/api1/b258
Control panel: http://databoom.space/cpanel.html

пишет
--------------------
Hi!
I am try login datebase use url: https://t258.databoom.space/api1/sampledb/collections/allobjects 
by using Root login and Root password, but I can not to do this.
I try to login using username and password from control panel. And  I can not to login too.
What login and password I must using?

С уважением, Турышева Е.В.

Девушка не может войти в свою базу (вернее, она, конечно, неправильно делает, набирает URL базы). Но, это не должно вызывать ошибки. Раньше это вызывало содержимое базы, пустое, если база пуста. Теперь вызвается диалог ввода пароля, потом ошибка SSL, потом вообще отлуп молча.

**Comment by ixdu** [comment]
Так, по порядку. Она не может войти в контрольную панель и спрашивает какой логин исопльзовать - любой, email или tномер. Сейчас только зашёл всё ок.
Дальше, она пытается зайти не в свою базу, а в базу sampledb, которой у неё нет, а есть только b258. Если пройти по https://t258.databoom.space/api1/sampledb/collections/ то будет написано что такой базы нет.
Возможно раньше, и если добавить allobjects тоже пишет тоже самое, но когда раньше? Код работы базы в этом месте не менялся. 
Да, можно возвращать информацию о том что базы не существует, сделаю,

**Comment by Databoom** [comment]
У нас раньше эта sampledb была доступна всем на чтение. Чтобы изучать примеры. Сейчас разве не так?

**Comment by ixdu** [comment]
Нет, эта база существует у пользователя samples. То есть она доступна по samples.databoom.spce/api1/sampledb. У других пользователей этой базы нет.
