### ISSUE TITLE
ошибка при регистрации нового пользователя

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#106]
зарегистрировался под vc@databoom.space (проверил еще раз под vc@nitorsbase.com)
Получил после долгого ожидания такую страницу
![image](https://cloud.githubusercontent.com/assets/13114324/13247365/37425bf8-da2a-11e5-882e-94c26132a2f6.png)
Письмо тем не менее пришло. 

Надо починить срочно

**Comment by ixdu** [comment]
поправил.
