### ISSUE TITLE
Ошибка при доступе к базе по URL 

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#108]
1. Захожу в CP под t231
2. ввожу URL своей базы https://t231.databoom.space/api1/b231/ - все в порядке, показывается JSON с данными базы. 
3. хочу посмотреть коллекции. Ввожу URL https://t231.databoom.space/api1/b231/collections/allobjects
возникает авторизационный диалог браузера
После ввода логина-пароля показываются коллекции. 

Это нормальное поведение? Ведь с точки зрения пользователя, я уже ввел данные логина и пароля, и могу смотреть свои коллекции? 

Если нормальное - то надо это как-то объяснить, почему, нажимая на кнопки я могу гулять по коллекциям, а нажав URL - нет.

**Comment by ixdu** [comment]
Да, это сейчас нормальное поведение. Потому что происходит авторизация по разному. 
Админка авторизуется через session login и получает токен, используя который посылает все запросы.
Ежеле пользователь берёт и нажимает на прямую ссылки или вводит её в адресную строку, то происходит авторизация через http basic, которая и запрашивает логи и пароль.
То есть сущесвует несколько независимых друг от друга способов авторизоваться. Не так давно обсуждали этот вопрос, нужно думать как это всё причесать до понятного пользователю и главное удобного вида.
