### ISSUE TITLE
При регистрации нового пользователя надо сбрасывать пароль, если регистрация не удалась

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#110]
Сейчас если databoom тебе написал, что такой Email уже зарегистрирован, то это поле сбрасывается, а поле пароля и подтверждения пароля остаются.

**Comment by ixdu** [comment]
На самом деле ни одно не сбрасывалось, видимо это какая-то особенность браузера.
Теперь сбрасываются все поля.
