### ISSUE TITLE
При добавлении колонки возникает дополнительная колонка при определенных условиях

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#111]
Добавил колонку assignment в Grid View, присвоил Gary. 
пошел в JSON view
включил режим редактирования
Нажал contorl F чтобы найти контекст Gary
Нашел. 
Тут же не нажимая ничего сразу нажал Grid View. Получил результат
![image](https://cloud.githubusercontent.com/assets/13114324/13259192/622a4ec4-da67-11e5-80f9-1863f4e36cf8.png)
После нажатия кнопки Reload эффект пропал. 
Возможно, надо запретить нажимать что-либо кроме save и cancel в режиме редактирования.

**Comment by ixdu** [comment]
Не думаю что нужно запрещать. Переход туда-сюда вполне обычное дело и с таким успехом человек может нажать просто на назад( та что переход на предыдущее место, на некоторых даже клавиатурах есть такая кнопка).
Баг поправил.
