### ISSUE TITLE
нет кнопки удаления колонки

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#112]
Это так задумано?

**Comment by ixdu** [comment]
В грид режиме? Есть добавление, но нет удаления? Ну изначально не планировалось и добавления). Реализовать удаление колонки возможно, если это нужно, то сделаю.

**Comment by Databoom** [comment]
По идее, надо. Раз есть добавление. Соответственно...
1. наверное в заголовке надо крестик ставить рядом с названием колонки? 
2. тогда все колонки должно быть можно удалять, не только созданные. 
3. при удалении колонки надо понять, что делать, если данные в колонке уже есть. Наверное, надо спрашивать: "The column you are about to delete is used by some objects. Would you still like to delete the column?"

**Comment by ixdu** [comment]
Добавил удаление, но не крестиком, а через column menu, которое наконец заработало.
Да, удалять можно любые колонки, кроме id.
