### ISSUE TITLE
Кнопку удаления строки в Grid View лучше вынести за пределы таблицы

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#113]
Или как-то еще зафиксировать ее на экране. Потому что если колонок много - замучишься скроллить туда-сюда.

**Comment by ixdu** [comment]
Посмотрю что можно сделать.

**Comment by Databoom** [comment]
Я думаю, это не так срочно. Недельку потерпит

**Comment by ixdu** [comment]
Поскольку зафиксировать не удаётся, то нашёл другой вариант. Теперь можно выделять строки в гриде, в том числе используя ctrl, то есть листать и добавлять выделенные строки. Затем нажать на кнопку actions и выбрать delete. Так можно удалить сразу группу объектов. В дальнейшем можно будет добавить и другие действия, вроде перевода в другую коллекцию и тд.
