### ISSUE TITLE
При редактировании ID происходит размножение объектов

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#114]
1. Вхожу в Grid View. 
2. Меняю несколько объектов руками с помощью редактирования ID на другие, не GUID-ы. 
3. кликаю на крестик удалить объект - вижу такую картину: 

![image](https://cloud.githubusercontent.com/assets/13114324/13278606/c745e3e2-dae2-11e5-91ad-37389a1cfb7d.png)

То же самое было бы, если бы я переключился на JSON потом обратно. 

Похоже, что при редактировании объекта не происходит запись результата в базу.

**Comment by ixdu** [comment]
Нет, происходит. Просто те id, что отображаются в гриде являются и теми id, по которым объекты находятся в базе. Иными словами, когда у объекта изменяется id в грид и затем он сохраняется, он уже новый объект с новым id. Старый же ни куда не девается. 
Сделал как ожидается, теперь объекту можно менять id в grid.
