### ISSUE TITLE
При отмене редактирования в JSON view тем не менее, отмененные действия отображаются. 

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#115]
1. Иду в JSON View. 
2. создаю копию объекта. 
3. генерирую для него ID. 
4. потом отменяю редактирование, нажав на карандаш. 
5. редактирование отменяется, но объект остается. Потом при переключении на Grid View он пропадает.

**Comment by ixdu** [comment]
Поправил, осталось иконку найти подходящую для переключения обратно в ридонли)
