### ISSUE TITLE
Если в коллекции (grid) создать колонку с числовым названием, что она не работает.

### ISSUE THREAD

**Issue by vsalnikov** [Databoom/work#116]
Если в коллекции (grid) создать колонку с числовым названием, что она не работает.

Например, создать колонку с названием "6767". Колонка создается, но заполнить её нельзя.
Ожидаемое поведение: запрет создания таких колонок ИЛИ корректная работа таких колонок.

**Comment by vsalnikov** [comment]
При работе через JSON колонку такую создать можно. При этом в режиме грида её значения по-прежнему невозможно отредактировать.

**Comment by ixdu** [comment]
Хотя в json режиме можно создать поле, которое не является валидным идентификатором, делая это человек должен понимать зачем это ему нужно. По сути в таком случае грид ему не нужен.
Валидный идентификатор содержит только буквы, цифры и символ подчёркивания. Начинается с символа подчёркивания или буквы. Это необходимо, чтобы объекты и свойства можно было представлять как объекты в обычных языках вроде C++ или Java. Также имея поле, начинающееся с цифры по нему не получится отфильтровать в OData запросах и тд.

Посему в гриде запретил именовать колонки неправильно и добавил в диалог подробное описание как правильно называть.
