### ISSUE TITLE
во время набора запроса руками несколько раз возникает красная подсказка 

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#119]
во время набора запроса руками, например, hometasks?$filter=(priority eq 0),  несколько раз возникает красная подсказка 
![image](https://cloud.githubusercontent.com/assets/13114324/13312342/edb08a0e-dba6-11e5-90e0-50fca1aae0c3.png)
Выглядит назойливо. Можно ли что-то с этим сделать? 
Может быть кнопку запуска запроса поставить? Чтобы в другое время ничего не проверялось.

**Comment by ixdu** [comment]
Да, конечно можно. Можно сделать и чтобы кнопка была, она же рефреш или как раньше была run. Можно ещё чтобы по энтеру запускался.
Оно не проверяется, оно отсылается на сервер, отсюда и пара багов которые так долго висели. В общем этот онлайн посыл только добавляет сложностей)

**Comment by ixdu** [comment]
Сделал отправление запроса по кнопке, по изменению(когда теряет фокус или нажатие enter).
