### ISSUE TITLE
При сохранении булевого из js значения в личном кабинете показывается значение b1

### ISSUE THREAD

**Issue by vsalnikov** [Databoom/work#122]
При сохранении булевого из js значения в личном кабинете показывается значение b1

Код сохранения объекта
        db.save('car', { created_dt: new Date(), empty: true }).done(

**Comment by ixdu** [comment]
Оно не просто показывается, оно так хранится. То есть при сохранении в базу сохраняются b1 и b0 вместо true и false соответственно. При этом не важно из библиотеки или как-то иначе. На самом деле библиотека ничего не делает по части преобразования типов.
Вопрос в том на каком уровне происходит, на уровне C++ модуля или на уровне nitrobasejs, посмотрю.

**Comment by ixdu** [comment]
Где-то что-то побилось, фикс на это дело наложил, true-false снова показываются как надо.
Буду следить чтобы не слетало от обновления к обновлению.

**Comment by ixdu** [comment]
Опять двадцать пять. Теперь старые значение показывает нормально, а новые вообще не показывает и возвращает битый json, фуф.

**Comment by ixdu** [comment]
Новые показывает, старые тоже.

**Comment by vsalnikov** [comment]
Исправлено, вроде бы :)
