### ISSUE TITLE
При создании коллекции создается одноименный объект

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#123]
Создал коллекцию Trashlist, вижу:
![image](https://cloud.githubusercontent.com/assets/13114324/13421186/c769a3e4-df9d-11e5-9cfd-430ac9c4de04.png)

**Comment by ixdu** [comment]
Не одноимённый, а первый. При создании коллекции создаётся два объекта:

- сама коллекция, то есть объект с id коллекции, на который ссылаются другие объекты, являющиеся членами коллекции
- объект ссылающийся на коллекцию

Если не создать второй объект(строго говоря только он и создаётся, первый база создаёт сама), то и коллекции не будет видно. Коллекция видна, если на неё ссылается хотя бы один объект.
Хотя это уже обсуждали, но для истории записать важно.
