### ISSUE TITLE
При удалении последнего объекта из коллекции коллекция удаляется. 

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#124]

**Comment by ixdu** [comment]
договорились сделать предупреждение, когда удаляется последний объект что и коллекция идёт следом.

**Comment by ixdu** [comment]
Нет, предупреждение здесь выдавать не выйдет. Работать оно всё равно толком не будет. Если коллекция содержит данные, которые добавляются программно. То пока появилось предупреждение, в коллекцию могут быть добавлены ещё объекты. Поэтому решение с тем, что коллекция имеет отдельное поле более правильно, а для этого есть отдельный тикет.
