### ISSUE TITLE
При удалении account-а база не чистится

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#125]
При удалении Account-a по красному крестику, account удаляется, но база остается почему-то за ним и база не чистится. В результате при повторной регистрации я получаю весь тот мусор, который насоздавал.

**Comment by ixdu** [comment]
Теперь чистится, но возможно это ещё не конец попутно решению этого бага и создания тестового сервера накопал немного проблем)

**Comment by ixdu** [comment]
откатил некоторые опасные изменения, так что скорее всего пять не чистится полностью:(

**Comment by ixdu** [comment]
Более-менее нормальное решение найдено, работает. Может ещё будет что-то всплывать, буду наблюдать.
