### ISSUE TITLE
Раздел Samples сайта databoom надо почистить от странностей

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#128]
Полазил - обнаружил ряд странностей. Скорее всего надо просто почистить. 
1. Когда входишь - показывается пустой экран. 
![image](https://cloud.githubusercontent.com/assets/13114324/13452270/7ab7cb42-e057-11e5-8314-bd3ec9d73eb3.png)
Возможно, надо какой-то текст придумать? Может быть сделать обзор, типа
"...А вот как писать на databoom приложения. Например, ... <кнопочка перехода на этот пример> ... а если вам надо ... <кнопочка>..." Ну что-то в этом роде. Предлагаю подумать
Разделение на "Using Controls" и "Simple Apps" какое-то условное. И, признаться, раздражающее. 
2. Using Controls - пустой. 
![image](https://cloud.githubusercontent.com/assets/13114324/13452455/f3898d3e-e058-11e5-9f54-23571e0126d3.png)
3. Editing Data пустой 
![image](https://cloud.githubusercontent.com/assets/13114324/13452361/23e951fe-e058-11e5-89dd-55c5b2f2e176.png)

**Comment by ixdu** [comment]
думаю элементы сгруппировать по используемому фреймворку. То есть как сейчас в Using Controls, только вывести на верхний уровень. Соответственно из simple apps на вернихй уровень выведено будет две категории jQuery и Angular. Всё равно эти "простые" приложения не сильно проще других сэмплов.

**Comment by Databoom** [comment]
Посмотрел сегодня - ни один пример, за исключением 3 Todo приложений, не отображается нормально. Надо хотя бы это исправить, бог с ними с улучшениями.

**Comment by ixdu** [comment]
Странно, может codepen глючил, всё отображается как и раньше, но посмотрю ещё.

**Comment by ixdu** [comment]
Нет, с codepen всё нормально. При загрузке через https почти все примеры не работали, потому что тянули зависимости с http. Часть зависимостей в принципе нет по https, поэтому теперь такие зависимости хостятся у нас. Примеры теперь работают как через http, так и через https.

**Comment by ixdu** [comment]
Добавил пример 3й пример с kendo.

**Comment by ixdu** [comment]
Содержимое обоих подменю вынес в основное меню, about теперь показывается, ссылки поправил, кое-где ещё поправил ошибки.
