### ISSUE TITLE
Некоторые примеры грузятся ну страшно долго 

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#129]
Некоторые примеры грузятся ну страшно долго (например, оба DevExpress примера, Webix, Syncfusion, jqGrid)

**Comment by ixdu** [comment]
Правильнее сказать они не грузились, а просто ожидали загрузки скриптов. Примеры то перенесли на полимер, а зависимости для примеров остались на старом сайте:) Перенёс, всё работает.
