### ISSUE TITLE
При добавлении коллекции в разделе Groups пишет undefined

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#130]
1. В разделе Groups добавляю группу, даю ей имя. 
2. кликаю + чтобы добавить коллекцию
3. выбираю коллекцию - вместо имени коллекции получаю undefied
![image](https://cloud.githubusercontent.com/assets/13114324/13452672/2b353c7c-e05b-11e5-89d4-1556cb8c7d71.png)

**Comment by ixdu** [comment]
поправил поведение в нескольких случаях, не позволяет выбирать коллекцию, если все добавлены и не добавляет ничего если выбрано(а то получалось undefined).
Воспроизвести случай не могу теперь, надеюсь решилось.
