### ISSUE TITLE
При сохранении изменения JSON сообщает об ошибке, но не пишет где

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#131]
![image](https://cloud.githubusercontent.com/assets/13114324/13453056/32d87f40-e05e-11e5-8a0c-6552c2d24022.png)

**Comment by ixdu** [comment]
Подключил клиентский парсер, пока только для сохранения в json редакторе. Так сказать проба пера. Справляется даже с десятком мегабайт, ошибки показывает понятно.
