### ISSUE TITLE
Если я удаляю account потом снова создаю, то в базе нет коллекции tasklist

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#132]

**Comment by ixdu** [comment]
по сути это #125 баг, просто проявляется он по разному. Суть его в том, что база не удаляется полностью, часть её остаётся в процессах. При пересоздании аккаунта происходит наложение. Хотя проверить не лишне, вдруг что ещё.

**Comment by ixdu** [comment]
должно починиться
