### ISSUE TITLE
После загрузки файла JSON в базу куда-то пропали около 100 строк

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#133]
1. загрузил файл out03.json
2. выгрузил с помощью copy/paste из @allobjects файл fact03.json

Надо проверить. Возможно, что все нормально, но я не знаю, как сравнить эти файлы. Порядок объектов разный, поэтому простое текстовое сравнение не

[out03.json.txt](https://github.com/Databoom/work/files/155570/out03.json.txt)
[fact03.json.txt](https://github.com/Databoom/work/files/155569/fact03.json.txt)

возможно. 
В исходном файле на 100 строк больше, чем в выгруженном из базы.

**Comment by ixdu** [comment]
Полностью идентичны, перепроверил несколько раз, написал скрипт проверки и выгрузки в одним и тем же способом. Прикладываю выгрузку из обоих файлов, она идентична по размеру и содержимому.
[diffout1.txt](https://github.com/Databoom/work/files/171575/diffout1.txt)
[diffout2.txt](https://github.com/Databoom/work/files/171576/diffout2.txt)
