### ISSUE TITLE
Было бы удобнее, чтобы при редактировании JSON, результат сначала бы обрабатывался через eval(). К такому варианту JSON меньше требований

### ISSUE THREAD

**Issue by vsalnikov** [Databoom/work#134]
Было бы удобнее, чтобы при редактировании JSON, результат сначала бы обрабатывался через eval(). К такому варианту JSON меньше требований

Нужно рассмотреть эту возможность. Нет ли подводных камней?

eval() предъявляет меньше требований к JSON-строке. Позволяет писать без кавычек, использовать разные типы кавычек и т.п.

**Comment by ixdu** [comment]
Подводные камни есть и мы только сейчас их встречаем. Наоборот сейчас склоняемся к отдельному парсеру JSON на клиенте, потоковому, чтобы проверять разные случаи, которые для базы не ахти.
В общем  случаене всякий JSON корректен для базы, отсюда возникают всякие проблемы при импорте. Например использование null приводит к ошибке, также есть особенности с хранением булевого типа. 
Eval ещё имеет проблемы в отладке, мало того что сейчас и так с этим проблема.
С другой стороны последний стандарт JSON также позволяет писать без кавычек, с разными типами кавычек, значит мы к этому придём.
В общем тут надо подумать.

**Comment by ixdu** [comment]
В общем такого не будет, однако доработки в парсере чтобы смягчить требования возможно будут.

**Comment by vsalnikov** [comment]
Ок.
