### ISSUE TITLE
При редактировании пустого множества в JSON нужно показывать пустой массив []

### ISSUE THREAD

**Issue by vsalnikov** [Databoom/work#135]
Если перейти по ссылке в гриде (ссылка - more), то если массив ссылок пустой, то получаем редактирование пустого множества.

Если перейти к редактированию JSON для данного пустого множества, то получаем пустую строку. Пользователь может не догадаться написать свойства объекта в массиве.

Ожидаемое поведение: в редакторе JSON пустого множества должны быть показаны квадратные скобки [] - типа пустой массив.

**Comment by ixdu** [comment]
Скобки были специально убраны по просьбе Виктора, так что мнения разные на этот счёт, надо обсудить.

**Comment by Databoom** [comment]
давайте оставим скобки и если надо, другие служебные символы.

**Comment by ixdu** [comment]
поправил, скобки на месте.
Других служебных там не будет, это чисто json.
