### ISSUE TITLE
Если в меню админки на пункте меню нажать "Открыть в новой вкладке" - то не работает. Новая вкладка зависает.

### ISSUE THREAD

**Issue by vsalnikov** [Databoom/work#137]
Если в меню админки на пункте меню нажать "Открыть в новой вкладке" - то не работает. Новая вкладка зависает.

**Comment by ixdu** [comment]
Есть такое, вот вам и SAP, поидее это ко всем случаем где маршруты используется применимо. То есть везде где ссылки вида /access, /collections, а не /cpanel.html#!/access, cpanel.html#!/collections.

**Comment by ixdu** [comment]
Теперь работает.

**Comment by vsalnikov** [comment]
И правда :)
