### ISSUE TITLE
В экспортируемом JSON может быть стоит сначала коллекции выдать, потом объекты?

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#138]
В общем, не совсем ясно, стоит ли. 
По крайней мере, я вижу, что у меня задачи идут вперемешку с коллекциями задач. 
Хотя могут быть сколь угодно не очевидные случаи. Так что, просто подумать.

**Comment by ixdu** [comment]
В этом json нет порядка и он и не предполагался как мне кажется. Это просто дамп, который можно потом загрузить обратно, это главное.
Сделать можно, но важно понять зачем это нужно. Поскольку дамп это массив, порядок элементом можно задать, но это значит либо нужно делать на стороне С++ части либо уже потом, хоть на клиенте.
