### ISSUE TITLE
Не закачиваются социальные сети

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#140]
По этому адресу
https://dl.dropboxusercontent.com/u/21937378/Friends.rar
Лежат 3 файла - все графы друзей. 
Ни один не грузится. 
Пытался грузить через раздел databases

**Comment by ixdu** [comment]
Не всякий произвольный json может быть загружен в базу. В данном случае там как минимум есть там много полей со значением null, если все null заменить на что-нибудь другое, например на "" или на 0, то первый добавляется.
Второй и третий подпадают под баг с заливкой больших файлов.

**Comment by Databoom** [comment]
null что ли нелегальный символ? 

Тогда можно было бы при первом встреченном нелегальном символе выдавать место и причину непрохождения? 

А с большими файлами по-прежнему проблема? 
Это Сережин баг?

**Comment by ixdu** [comment]
Почему-то нелегальный, точнее сказать проходить он проходит но база его интерпретирует по разному. Если вставить его в поле в запросе, то объект пропадает, а иногда и соседние:) Если uploadjson, как в этом случае, то ошибка возвращается. Почему, надо проверять. Потоковой json парсер для клиента я нашёл, чтобы встроить его и сделать с его использованием проверку на любые недопустимые значения. Но это требует времени.
Да, с большими файлами по прежнему проблема, потому что всё сразу вылечить не могу) Вот и тут поднакопились баги уже. Поскольку сейчас в основном тем и занимаюсь что ищу проблемы, то и с большими файлами скоро выясню в чём дело.

**Comment by vsalnikov** [comment]
Коллеги. Может лучше исправить баг в базе, чтобы она принимала null корректно?

**Comment by ixdu** [comment]
Лучше, нужно править если это возможно. Сергею отписался, но там такие нюансы ещё есть и желательно их все поправить конечно.

**Comment by Databoom** [comment]
Сергей поправил?

**Comment by ixdu** [comment]
Сейчас обкатываем на тестовом сервере и да, там загружается даже тот на 7мб, не модифицированный.
Там ещё пара косяков, как минимум один из них нужно решить до переноса на основной сервер, потому что база виснет.
Из относящегося к этому тикету не решённым пока остаётся ошибки, если они есть в файле - ничего внятного не сообщается. Тоже в процессе решения.

**Comment by ixdu** [comment]
Теперь работает.
