### ISSUE TITLE
Сломался скрипт cst, который давал статистику по логу

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#141]
URL такой: 
 http://admin.databoom.space/cst

**Comment by ixdu** [comment]
Обращение к базе возможно только по https. Связано это с тем, что пароли, даже если используется логин с генерацией токена(а следовательнои токен(, передаются в открытом виде. Не говоря уже о возможности работать с базой используя http basic auth, а там каждый раз передаются логин и пароль. Пишу это сюда,  хотя уже обсуждали, для истории).

Скрипты починил, шапку тоже починил всё работает.
