### ISSUE TITLE
Невозможно создать новый объект в пустом массиве ссылок, используя табличный интерфейс. Кнопка добавления не работает

### ISSUE THREAD

**Issue by vsalnikov** [Databoom/work#143]
Невозможно создать новый объект в пустом массиве ссылок, используя табличный интерфейс. Кнопка добавления не работает.

На картинке все видно.  Я перешел по ссылке из строки коллекции car
![image](https://cloud.githubusercontent.com/assets/17023659/13633896/f3c13b44-e602-11e5-9853-0bb411e999f1.png)

**Comment by ixdu** [comment]
Теперь возможно, но поскольку в гриде в связи с этим целая пачка изменений, то тестировать можно на тестовом сервере https://databoom.space:8001

**Comment by vsalnikov** [comment]
Есть недоработка.
Нажимаем Add Link, затем создаем колонку "collections".
В поле collections, вводим, например "test123sd". После ввода в ячейке отображается значение [Object object]
Это работает при условии, что в массиве ссылок ранее не было ни одной ссылки.

Пока не закрываю.

**Comment by ixdu** [comment]
Да, поправлю, сейчас как раз работаю над изменением логики диалога добавить столбец, он будет давать выбор типа, для collections он должен быть links.

**Comment by ixdu** [comment]
Добавил поддержку типов в диалог создания столбца. Теперь можно выбрать из string, number, boolean и objects.  Для collections выбранный тип игнорируется и создаётся правильный.
