### ISSUE TITLE
Удаление объекта из массива ссылок в CPanel удаляет все ссылки на данный объект из других объектов

### ISSUE THREAD

**Issue by vsalnikov** [Databoom/work#144]
Два объекта car1 и car01 ссылаются на один объект car_trade2.
В CPanel в коллекции car в гриде нажимаю кнопку More в строке объекта car1.
Показывается список связей объекта car1 по полю trades.
Нажимаю кнопку "Удалить". Выбираю ONLY THIS. Объект удален из массива ссылок не только у car1, но также и у car01
Было:
```
{
    "id": "car1",
    "collections": [
      {
        "id": "car"
      }
    ],
    "trades": [
      {
        "id": "car_trade2"
      }
    ]
  },
  {
    "id": "car01",
    "collections": [
      {
        "id": "car"
      }
    ],
    "trades": [
      {
        "id": "car_trade2"
      }
    ]
  },

```

Стало:
```
  {
    "id": "car1",
    "collections": [
      {
        "id": "car"
      }
    ],
    "trades": []
  },
  {
    "id": "car01",
    "collections": [
      {
        "id": "car"
      }
    ],
    "trades": []
  },
```

**Comment by ixdu** [comment]
Не совсем верно, объект просто удалялся сам, а не ссылка на него. Что тянуло за собой любые ссылки на него. Это от того, что режима редактирования ссылок просто не было.
Реализовано, но тестировать на тестовом сервере https://databoom.space:8001
