### ISSUE TITLE
запоминать вид view в котором работал с коллекцией

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#145]
Бывают коллекции, которые невозможно показывать (бесполезно) в табличном виде (таких мало - но есть). например такая: 
![image](https://cloud.githubusercontent.com/assets/13114324/13701072/1fcbb0d6-e796-11e5-9688-6b3b62773e8e.png)
Поэтому, хорошо бы ее переключить однажды в JSON view и больше не возвращаться к этому вопросу. 
В качестве простого решения, имеет смысл просто помнить в каком view я работал с данной коллекцией и при следующем открытии показывать его.

**Comment by ixdu** [comment]
сделано, но только в рамках сессии)

**Comment by Databoom** [comment]
Естественно!
