### ISSUE TITLE
Пустая база содержит коллекции

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#147]
1. Первоначально база пустая. 
2. Я в Todo приложении завожу задачи в 2 разных коллекциях
3. удаляю эти задачи в приложении. То есть, приложение пустое, задач нет. 
4. иду в CP, в разделе collections вижу пустые коллекции
![image](https://cloud.githubusercontent.com/assets/13114324/13775814/c5ae7802-eab7-11e5-8d68-40dc678d8d3d.png)
Вопрос, собственно, такой: это будем считать нормальным поведением? Тогда надо задокументировать. То есть, мы допускаем в базе данных пустые коллекции? Смысл есть?

**Comment by ixdu** [comment]
Смысла большого нет, потому как коллекция создаётся автоматически при создании объекта, который ей будет принадлежать.
Это отличается от большинства SQL баз и да и документо-ориентированных баз тоже, где сначала создаётся место куда кладутся данные(коллекция, таблица и тд), а затем туда данные добавляются.
Здесь есть логика, и она в том что у нас коллекции это просто объекты. А значит они сами могут содержать данные. То есть у нас может быть объект, который связан с несколькими реальными объектами с помощью ссылок. И вот такие реальные объекты надо отличать от коллекций. Опять же возвращаемся к тому вопросу, что нужно по чётче выделить коллекции, чтобы их объекты были вроде 
`{
  "is" : "collection",
 "id" : "worktasks"
}`
В таком случае можно будет удалять такую коллекцию, если удаляется последний объект.

**Comment by Databoom** [comment]
Я понял, то есть типы объектов надо вводить. А это не опасно? Не потеряем гибкости из-за этого? 
Может быть коллекцию детектировать по тому, что это объект, который
а) имеет только id
б) находится вне коллекций
Тогда, если никакой объект на нее не ссылается - такую коллекцию удалять. 
Если так?

**Comment by ixdu** [comment]
Опасности тут нет, потому что это добавление, а не исключение. Просто у объектов коллекций будет одно или пара полей. Ничему мешать это не будет, а зато позволит например показывать пустые коллекции.
А вот считать любой объект, который имеет только id пустой коллекцией - вот это уже может быть опасно. По крайней мере это явный запрет иметь пустые объекты. А пустые объекты, мало ли, может кому и понадобятся).

**Comment by Databoom** [comment]
А Слава что говорит?

**Comment by Databoom** [comment]
Коллекция - это не обязательно пустой объект.
Коллекцией может быть вообще любой объект. Например, компания, отдел или вообще конкретный человек.

**Comment by Databoom** [comment]
Ссылка "collections" ничем не отличается от ссылки типа "authors" - за одним выжным исключением вы можете обращаться к коллекции через URL по ее имени. Но это просто сокращение записи - точно также не сложно обратиться и списку авторов.
