### ISSUE TITLE
Непонятка с группами

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#149]
1. Иду в Groups, в Card view. 
Дальше по-разному, но после действия я каждый раз жму кнопку "Refresh", при этом каждый раз действие вызывает неожиданный результат. Чаще всего изменения пропадают. Но бывает по-разному. 
a) Создаю группу, жму "Refresh"
б) создаю коллекцию в существующей группе, жму "Refresh"
в) Создаю группу, создаю коллекцию в ней, жму "Refresh"

Может быть сделать кнопку "сохранить в базе", как везде? 
Или, сделать так, чтобы при Refresh не терялись сделанные изменения?

**Comment by ixdu** [comment]
Можно добавить, но refresh здесь вообще никак не влияет на сохранение. Сохранение сделано при любом изменении. То есть добавление групп, коллекций, прав коллекций приводит к автоматическому сохранению. Refresh здесь только потому, что можно изменить группы из другого места и в таком случае обновить.

**Comment by Databoom** [comment]
Да, раз так - то надо только пофиксить.

**Comment by ixdu** [comment]
Сохранение работает как следует. Убрал кнопку добавление группы вниз, refresh убрал она тут не нужна. Новая группа также появляется внизу. При перещёлкивании между json режимом и cards карточки остаются на месте(раньше карточка сверху уезжала вниз, потому что новые группы добавляются в конец)
