### ISSUE TITLE
Очень долго загружается страница панели управления.

### ISSUE THREAD

**Issue by vsalnikov** [Databoom/work#150]
Очень долго загружается страница панели управления.
http://databoom.space/cpanel.html#!/account

Это особенно заметно, когда открываешь страницу в новой вкладке.
Если просто обновлять страницу - то еще приемлемо.

У нас там нет никаких больших данных. Должно грузиться почти моментально.

![image](https://cloud.githubusercontent.com/assets/17023659/13845140/f8318308-ec4e-11e5-954e-263e55b00fb7.png)

**Comment by vsalnikov** [comment]
И еще. 158 запросов к серверу при каждом обновлении страницы - это вроде бы много! Скажите, если я неправ.

**Comment by ixdu** [comment]
Увы, выбранная технология(полимер) накладывает отпечаток. Грузится долго. Причём в firefox ещё долго строится сам ui(по сути компилируется на клиенте:)). 
Да, много, в ближайшее время завулканизирую основные страницы, будет пара десятков запросов, чуть по лучше станет и с загрузкой)
