### ISSUE TITLE
При открытии Панели управления в новой вкладке - требует заново вводить пароль.

### ISSUE THREAD

**Issue by vsalnikov** [Databoom/work#151]
При открытии Панели управления в новой вкладке - требует заново вводить логин/пароль.

Это не нормально. Любой сайт (гугл почта, фейсбук, вконтакт и т.п.) работает так: если на одной вкладке браузера я вошел в систему, то новой вкладке этого делать уже надо.

**Comment by vsalnikov** [comment]
Проверил это в FireFox. Если подтвердить сохранении паролья браузером, то при повторном открытии вкладок пароль не требуется. В Chrome так не получается сделать.

**Comment by ixdu** [comment]
Да, есть такое, логин использует исключительно localstorage и sessionstorage, их поведение отличается от поведение постоянных и временных куков соответственно.
Сделаем как у всех:)

**Comment by ixdu** [comment]
сделал время временной сессии длиной в час. Во время часа можно открывать новые вкладки всё будет ок. Но тут вопрос, как удобнее, чтобы просто было ограничение в час(как сейчас) или час простоя. То есть если человек не делает ничего в панели час, то сессия оканчивается.
