### ISSUE TITLE
Username у пользователя не сохраняется.

### ISSUE THREAD

**Issue by vsalnikov** [Databoom/work#152]
Если изменить username у пользователя, то оно не всегда сохраняется.

Вот, поменял username.
Строка с красной галочкой осталась.
Если я обновляю страницу, то изменение username пропадает, откатывается к предыдущему сохраненному варианту.

Кроме того, если я поменяю username, а потом и группу у этого пользователя, то создается копия пользователя с новым username и группой.
**
Похоже, что username просто нельзя поменять!**

![image](https://cloud.githubusercontent.com/assets/17023659/13845537/b4142ccc-ec51-11e5-858a-ef979109a981.png)

**Comment by ixdu** [comment]
не работала и смена пароля). Починено.
