### ISSUE TITLE
Если в личном кабинете перейти на пункт Projects -> Todo, то зачем-то просит ввести какой-то пароль

### ISSUE THREAD

**Issue by vsalnikov** [Databoom/work#153]
Если в личном кабинете перейти на пункт Projects -> Todo, то зачем-то просит ввести какой-то пароль.

1) Что это за пароль и для чего его вводить не понятно.
(Я знаю, а вот пользователь может и не знать)
2) Раньше такого не было.
3) Зачем вводить пароль к базе, я если и так уже вошел в личный кабинет и могу править базу напрямую?

![image](https://cloud.githubusercontent.com/assets/17023659/13845647/6bf6f54a-ec52-11e5-84c6-004909bfbb95.png)

**Comment by ixdu** [comment]
Раньше не было потому, что был пользователь default, который был удалён.
Все примеры приложений используют этого пользователя и сами логинятся, не используя общий логин панели. Это видно из исходников.
Сделано так, потому что их можно скачать, не дописывая туда кода для подключения к базе.
Наверное, тут стоит как-то переработать, возможно совсем вынести это в отдельную кнопку скачать, а не раздел.

**Comment by vsalnikov** [comment]
Понятно. Я сам удалил этого default, поэтому все перестало работать.
Было бы неплохо "default" переименовать в "admin". Так было бы понятнее и привычнее.
