### ISSUE TITLE
Когда в CPanel переходишь на раздел Databases, то он не подсвечивается.

### ISSUE THREAD

**Issue by vsalnikov** [Databoom/work#154]
Когда в CPanel переходишь на раздел Databases, то он не подсвечивается.

![image](https://cloud.githubusercontent.com/assets/17023659/13845757/152ed3f8-ec53-11e5-9e9b-dc365c8de0e6.png)

Разделы Account и Queries подсвечиваются, когда мы в них.

![image](https://cloud.githubusercontent.com/assets/17023659/13845743/f8fdf0ce-ec52-11e5-9247-15515ad8433b.png)
![image](https://cloud.githubusercontent.com/assets/17023659/13845746/002e3b60-ec53-11e5-915b-46df5ea5696f.png)

Остальные разделы так не подсвечиваются.

**Comment by ixdu** [comment]
Меню полностью переписано без полимера, нормальное выделение сделано. Полимерные компоненты касающиеся меню удалены из сборки.

**Comment by ixdu** [comment]
Дополнительные доработки меню. Отрываются и закрываются нормально. Теперь полностью работает через route, а значит в перспективе при открытии коллекции в другой вкладке коллекция будет выделяться. Пока это не доработано, как дойдут руки до переработки collections_manager будет и это.
