### ISSUE TITLE
При сохранении коллекции из двух объектов, поле "name" одного из них меняется на true

### ISSUE THREAD

**Issue by ivanmart** [Databoom/work#155]
При попытке сохранения следующих данных (в коллекции "test2"), значение "name" объекта "b" изменяется на true:

<pre><code>[
  {
    "id": "c7d0cceb-c967-4d17-a3c3-ba61b5cc79c3",
    "name": "a",
    "relpeople": [
      {
        "id": "6bdc8a-37cc-438b-85e7-2ebbeabda2"
      }
    ],
    "collections": [
      {
        "id": "test2"
      }
    ]
  },
  {
    "id": "6bdc8a-37cc-438b-85e7-2ebbeabda2",
    "name": "b",
    "collections": [
      {
        "id": "test2"
      }
    ]
  }
]</code></pre>

Точно так же невозможно установить имя "b" для объекта и в режиме Grid view: вводишь "b" - изменяется на true.

**Дополнение:** это происходит только с буквой "b" а так же со словами, начинающимися на "b". если вводить другие буквы - значение сохраняется.

**Comment by ixdu** [comment]
да, это баг работы с bool, внутри они хранятся как b0 и b1, почему-то это вылезло наружу, будем решать)

**Comment by ixdu** [comment]
Почти пофикшено, все значения кроме b1 и b2 сохраняются нормально на тестовом сервере. На основном после обновления будет также

**Comment by ixdu** [comment]
Проблема решена. Однако если строка ровна b0 или b1, то она превратится в false и true соответственно. С другими начиющимися с b строками всё будет ок. Так будет ещё какое-то время)

**Comment by Databoom** [comment]
а какое время так будет? С чем это связано?

**Comment by ixdu** [comment]
Как не пофиксим, просто причину не нашли пока. Поэтому и не понятно.

**Comment by ixdu** [comment]
Работает как положено
