### ISSUE TITLE
Установка ссылки на объект удаляет ссылку в другом объекте

### ISSUE THREAD

**Issue by ivanmart** [Databoom/work#156]
<pre><code>
[
  {
    "id": "c7d0cceb-c967-4d17-a3c3-ba61b5cc79c3",
    "name": "a1",
    "relpeople": [
      {
        "id": "6bdc8a-37cc-438b-85e7-2ebbeabda2"
      }
    ],
    "collections": [
      {
        "id": "test2"
      }
    ]
  },
  {
    "id": "6bdc8a-37cc-438b-85e7-2ebbeabda2",
    "name": "a2",
    "collections": [
      {
        "id": "test2"
      }
    ]
  }
]
</pre></code>

У объекта "a1" установлена ссылка на объект "a2", теперь надо у объекта "a2" установить ссылку на "a1", т.е. необходимо выполнить PUT-запрос к коллекции test2 с объектом "a2", содержащим привязку к объекту "a1":

curl -i -X PUT -H "Authorization: Basic ZGV2MTpkZXYx" -H "Content-Type: application/json" -d "{\"id\":\"6bdc8a-37cc-438b-85e7-2ebbeabda2\",\"name\":\"a2\",\"relpeople\":[{\"id\":\"c7d0cceb-c967-4d17-a3c3-ba61b5cc79c3\"}]}" "https://t286.databoom.space/api1/b286/collections/test2(6bdc8a-37cc-438b-85e7-2ebbeabda2)

Результат: создалась привязка от "a2" к "a1" но почему-то удалилась привязка у "a1"

**Comment by ixdu** [comment]
Теперь не просто удаляет привязку, а вообще отчищает объект, на который добавляется ссылка. Но над проблемой работают.

**Comment by ixdu** [comment]
Теперь работает как положено.
