### ISSUE TITLE
404 страница дефолтная от nginx, загружается ровно минуту

### ISSUE THREAD

**Issue by ivanmart** [Databoom/work#157]
В google проиндексированы страницы которых, вероятно, больше не существует. Например http://databoom.space/editgrid.html

Страница 404 ошибки грузится ровно минуту и представляет из себя стандартную nginx-овскую.

**Comment by ixdu** [comment]
Там не должно быть nginx, потому что запрос отрабатывает на данный момент nodejs, что в общем случае тоже неверно, но пока так, легаси так сказать)
Починил.

**Comment by ivanmart** [comment]
Я написал про nginx потому что в экране ошибки так написано:
![screen shot 2016-03-17 at 19 24 13](https://cloud.githubusercontent.com/assets/3215384/13899969/08035e82-ee0c-11e5-9536-ca29600c355c.png)

**Comment by ixdu** [comment]
Это я понял, поэтому и написал что не должно быть так, но так было) Неверно выразился.
