### ISSUE TITLE
Файл, прилагаемый к регистрационному письму, при запуске вызывает ошибку соединения

### ISSUE THREAD

**Issue by ivanmart** [Databoom/work#158]
"POST https://gmail.com.databoom.space/api1/b286/sesslogin net::ERR_NAME_NOT_RESOLVED", т.к. в нем указан такой адрес базы данных:

<code>var db = databoom('https://ivanborisych@gmail.com.databoom.space', 'b286');</code>

Eсли заменить url на правильный https://t286.databoom.space то не проходит авторизация - 401 Unauthorized. По всей видимости, связано с типом запроса POST, т.к. если выполнить GET-запрос на этот адрес "https://t286.databoom.space/api1/b286/sesslogin" то логин/пароль dev1:dev1 - подходит. Пробовал в Groups добавить права для метода POST - эффекта не дало.

**Comment by ixdu** [comment]
Больше к регистрационному письму не прилагаются файлы, это был старый вариант письма, оставшийся со старого сайта.
Сейчас приложения, настроенные на базу есть в контрольной панеле в разделе projects.

**Comment by ivanmart** [comment]
на databoom.space:8001 это осталось
