### ISSUE TITLE
Ссылки на библиотеки в примерах ведут на пустую страницу

### ISSUE THREAD

**Issue by ivanmart** [Databoom/work#161]
Ссылки на библиотеки в Projects ведут на пустую страницу

http://databoom.space/docs.html#!/doc-angular-part1
http://databoom.space/docs.html#!/doc-jquery-part1

Ссылка на описание messaging api в примере чата ведет на 404 (которая грузится 1 минуту)

http://databoom.space/docs/referense/messaging.htm

**UPD:** так же ссылки в App in 5 min ведут на пустую страницу

**Comment by ixdu** [comment]
Ссылки поправил, на messaging убрал пока не будет готов reference по библиотеке, тем более что messaging теперь будет частью основной библиотеки. Тикет по reference #17

**Comment by ivanmart** [comment]
http://databoom.space/cpanel.html#!/projects/5minapp тут ссылка "Kendo UI Grid Sample1" все еще ведет на пустую страницу

http://databoom.space/cpanel.html#!/projects/todo-jquery внизу ссылки Samples и Articles ведут на пустые страницы

тоже самое тут http://databoom.space/cpanel.html#!/projects/todo-angular

**Comment by Databoom** [comment]
http://databoom.space/docs.html#!/doc-angular-part1 - ПУСТАЯ
http://databoom.space/samples.html#!/about - ПУСТАЯ

**Comment by ixdu** [comment]
Починил, проблемы маршрутизации были. С http://databoom.space/docs.html#!/doc-angular-part1 не нашёл, где эта ссылка встречается? Она устарела, её надо заменить.
По samples есть отдельный тикет #128
