### ISSUE TITLE
Сломались коллекции в CPanel

### ISSUE THREAD

**Issue by ivanmart** [Databoom/work#164]
При тестировании разных вариантов запросов Kendo Grid в какой-то момент в CPanel/@allobjects получил ошибку "unexpected string" и далее CPanel перестала показывать коллекции, однако по rest api они присутствуют: https://t286.databoom.space/api1/b286/collections/sites

Прошу починить по возможности быстрее, т.к. нужна CPanel для отладки приложения.

**Comment by ixdu** [comment]
починил, но либо в базе ничего почти не было либо опять упало.

**Comment by ivanmart** [comment]
в базе было, в баге ссылка дана была. Просто что-то не понравилось базе в запросе. В следующий раз постараюсь сохранить запрос.
