### ISSUE TITLE
В Query сделать ссылку кликабельной

### ISSUE THREAD

**Issue by ivanmart** [Databoom/work#165]
Предлагаю в Query сделать ссылку кликабельной (target="_blank") или по крайней мере выделяемой. Сейчас чтобы её скопировать нужно открывать инспектор.
![screen shot 2016-03-18 at 18 30 13](https://cloud.githubusercontent.com/assets/3215384/13882693/ad1322a2-ed37-11e5-8322-f683128435fc.png)

**Comment by ixdu** [comment]
Сделано
