### ISSUE TITLE
непонятный basic http auth

### ISSUE THREAD

**Issue by ivanmart** [Databoom/work#166]
Сегодня вошел с другого инета, была открыта CPanel, запросила basic http auth, вводил туда все что указывал при регистрации, и после смены пароля, и то что в access control - не подходило. Вылечилось логаутом из CPanel и повторным входом через html-форму логина.

**Comment by ixdu** [comment]
На данный момент авторизация по токену, которая используется cpanel, сделана с привязкой токена к ip и без просрочивания, как бы следовало. Поэтому получается что при заходе с другого ip с прежним токеном фактически он становится недействительным.

**Comment by ivanmart** [comment]
Ага, наверное надо такого пользователя разлогинить и редиректить на страницу логина

**Comment by ixdu** [comment]
Пошёл другим путём. 
1. Дополнительно к основному механизму теперь реализовано молчаливое получение токена и молчаливый токен. Молчаливое получение гарантирует при логине невсплывание basic auth, а молчаливый токен гарантирует при любых операциях с базой если токен просрочен, то basic auth тажке не всплывает, а просто возвращается unauthorized, что уже дальше должно обрабатываеться клиентом правильно(например переполучать токен) 

2. Новая версия библиотки databoom теперь включает все операции, которые делает cpanel, то есть все они делаются через библиотеку. Сама же библиотека теперь поддерживает опциональный режим переполучения токена прямо в процессе операций, то есть если не получилось записать или прочитать что-то и выкинуло unauthorized, то идёт попытка получения токена и повтор операции. 
3. Код control panel также был сильно переработан, чтобы работать только через библиотеку и использовать механизм перелогина.

Итог: теперь при смене ip работоспособность control panel остаётся прежней в соответствии с настройками(если временная сессия то час, если keep, то бесконечно)

**Comment by ixdu** [comment]
проблема давно решена, как и написано в комментарии
