### ISSUE TITLE
в Welcome letter часть URL-ов http, часть https 

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#167]
Database: **https**://t310.databoom.space/api1/b310
Control panel: **http**://databoom.space/cpanel.html
Please find them at **http**://databoom.space/cpanel.html#!/projects/

Это все правильные URL-ы?

**Comment by ixdu** [comment]
Да, правильные. Но наверное лучше указать все https. А со временем и полностью отказаться от http для cpanel, оставить только https. Всё таки пароли. Поправлю на https

**Comment by ixdu** [comment]
Поправил на https.
