### ISSUE TITLE
 проблема хранения отрицательных чисел в databoom

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#168]
приложено приложение, в нем есть переменная
var minPriority
Если ей присвоить, скажем 99 - то задачи запоминаются, если присвоить 0 - то нет. 
Проблема в том, что новая задача получает приоритет minPriority-1. 
То есть, когда приоритет присваивается -1 - то база не хочет такое значение запоминать.

**Comment by Databoom** [comment]
[Bug_Todo_App_V01.html.txt](https://github.com/Databoom/work/files/181906/Bug_Todo_App_V01.html.txt)

**Comment by ixdu** [comment]
на тестовом сервере с новым парсером всё работает как надо, отрицательные числа сохраняются.
На основном же при отрицательных числах поля пропадают) Так что завтра всё будет ок)
