### ISSUE TITLE
Если в меню коллекций нажать "Открыть в новой вкладке" на кнопке коллекции - то открывается страница с ошибкой

### ISSUE THREAD

**Issue by vsalnikov** [Databoom/work#172]
Если в меню коллекций нажать "Открыть в новой вкладке" на кнопке коллекции - то открывается страница с ошибкой

![image](https://cloud.githubusercontent.com/assets/17023659/14045062/d80886e4-f2a7-11e5-9346-e60ccc9ebf9b.png)

**Comment by ixdu** [comment]
Тоже, что и #137. Изменилось лишь то, что сейчас несуществующие страницы дают ошибку. Пока  что открыть в новой вкладке нельзя любой пункт меню.

**Comment by ixdu** [comment]
починено как и #137
