### ISSUE TITLE
Если в CPanel в гриде коллекции перейти по ссылке More, то если ссылок, нет, то кнопка Add Row не работает и генерит ошибку в консоли

### ISSUE THREAD

**Issue by vsalnikov** [Databoom/work#173]
Если в CPanel в гриде коллекции перейти по ссылке More, то если ссылок, нет, то кнопка Add Row не работает и генерит ошибку в консоли.

Шаги воспроизведения:
1) Открыть коллекцию
2) Перейти по ссылке More в той строке коллекции, где ссылок нет
3) В открывшемся окне нажать Add Row

**Comment by ixdu** [comment]
дубликат бага #143 
Эта функциональность и не прорабатывалась раньше даже + ошибки в реализации put мешали. 
Это не то чтобы баг, а просто нет функциональности:) Скоро будет.

**Comment by ixdu** [comment]
Починено, смотреть пока на тестовом сервере, многовато изменений чтобы на продашин сразу ставить. https://databoom.space:8001
