### ISSUE TITLE
кавычки отображаются в виде escape последовательности

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#175]
В приложении (приложено) ввожу так:
![image](https://cloud.githubusercontent.com/assets/13114324/14102485/8f1e057c-f5a3-11e5-92bb-c8e0c3942e78.png)
После сохранения в базе вижу так: 
![image](https://cloud.githubusercontent.com/assets/13114324/14102519/c12918c2-f5a3-11e5-820d-22ee76e1766a.png)

**Comment by ixdu** [comment]
Проблема решена, на тестовом сервере можно попробовать, на основной переведу в выходные, потестирую пока ещё, поскольку не одна правка, ещё top починил, мало ли чего вылезет)
