### ISSUE TITLE
При заходе на страницы в Projects после удаления пользователя default требует http basic auth

### ISSUE THREAD

**Issue by ivanmart** [Databoom/work#177]
Если пользователь default удалён, просит http basic auth. При изменении в примере default на другого пользователя - после ввода каждой буквы открывается окно http basic auth.

**Comment by ivanmart** [comment]
А на странице http://databoom.space/cpanel.html#!/projects/5minapp нет логина default, но все равно просит http basic auth

**Comment by ixdu** [comment]
Похоже там на каждое изменение символа сделана перезагрузка приложения, забавно, поменяю.            
Что до 5minapp там логин есть, но у одного из двух приложений. У другого пока нет, но также будет скоро.

**Comment by ixdu** [comment]
Убрал перезапуск приложения на каждое изменение, добавил кнопку run для этих целей.
