### ISSUE TITLE
При клике на buttonrefresh фильтр сбрасывается

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#178]
1. вызываю коллекцию в табличном виде для Workatsks
2. ставлю фильтр Priority по возрастанию
3. нажимаю buttonrefresh - фильр сбрасывается.

**Comment by ixdu** [comment]
Поправил, единственный нюанс. Теперь, если где-то в другом месте добавить ещё столбец, а потом нажать в гриде на обновить, столбец не появится. Нужно будет выйти в меню или переключить режимы grid-json. Это недостаток кендо, он попросту не поддерживает добавление стобцов динамически. Найду как обойти, порешаю.
