### ISSUE TITLE
После ручного редактирования значений колонки фильтр неправильно отображает

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#180]
1. вызываю коллекцию Worktasks, жму фильтр Priority по возрастанию
2. руками правлю содержимое колонки Priority пытаясь руками расставить приоритеты по-своему. 
3. после этого снова жму фильтр Priority по возрастанию
4. получаю вот такую картинку
![image](https://cloud.githubusercontent.com/assets/13114324/14166948/58b09e4a-f720-11e5-8ae0-ae9abde5e11d.png)

**Comment by Databoom** [comment]
Причем refreshbutton не помогает

**Comment by ixdu** [comment]
Проблема была в том, что grid все поля по умолчанию считает string, поэтому сохранял числа и даже bool как стринг.
