### ISSUE TITLE
В разделе Collections кнопка Upload Collection работает неправильно

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#181]
Возможно, это больше концептуальный баг. 
Проблема вот в чем. 
- Я создал коллекцию Colors. 
- При заходе в collections я вижу такую картину. 
![image](https://cloud.githubusercontent.com/assets/13114324/14167250/85043554-f722-11e5-84dd-2a473430c8ba.png)
- вижу, что есть кнопка Download collection (напротив коллекции) но нет кнопки Upload Collection
- зато кнопка Upload есть в заголовке. Думаю, что она по ошибке там торчит, но нет, когда загружаю коллекцию через эту кнопку - получаю объект вне коллекции. 

Думаю, надо сделать так, иначе вообще ужас. 
![image](https://cloud.githubusercontent.com/assets/13114324/14167317/002ed8e2-f723-11e5-8577-ca260f1f4891.png)

**Comment by ixdu** [comment]
На данный момент этот upload полный аналог upload в database, то есть заливает json и если в объектах указана принадлежность коллекциям, то всё впорядке.

То есть работает это так: сначала выгружается коллекция с помощью download, затем загружается.
Это не концептуальный баг, а просто отсутствие такой функциональности как загрузить данные в коллекцию. Собственно об этом я писал в вики и да, это надо сделать.

**Comment by ixdu** [comment]
Сделана загрузка данных в конкретные коллекции. Работает немного медленнее, нежели заливать через database/uplod, но вполне приемлемо, залил даже мегабайт 5-6.
Единственный момент, прогрессбар не показывает процесс загрузки, поскольку заливка идёт через библиотеку, а в ней такой функциональности и не предусмотрено. Сделаем в библиотеке, заработает и здесь.

**Comment by Databoom** [comment]
только не забудь сделать прогрессбар потом
