### ISSUE TITLE
Еще раз про пустые объекты

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#183]
- в разделе коллекции завожу коллекцию Gmaps
- создается пустой объект. Это ладно. Можно объяснить. 
- после этого в коллекцию загружаю реальные данные. 
- пустой объект никуда не девается, хотя уже никакого смысла в нем нет. 
Это таки баг или фича? 
![image](https://cloud.githubusercontent.com/assets/13114324/14167844/aa92b044-f726-11e5-9dd2-1b286e2645b2.png)

**Comment by ixdu** [comment]
Это фича, без этого коллекция просто не определяется как коллекция. Нельзя получить список коллекций, если им не принадлежат объекты. Этот пустой объект такой же как и другие. Его можно редактировать или удалить.
Фича есть наследство rdf, где коллекций нет, это уже обсуждали, порешать этот момент можно только добавлением в объекты коллекций поля ``` is : "collection" ```` или что-то вроде этого

**Comment by Databoom** [comment]
А какие есть варианты? 
1.  поле is : "collection"
2. ???

**Comment by ixdu** [comment]
Да, ещё is : ["collection"] или как-нибудь extend : ["collection"]. Но в общем случае все эти варианты одинаковы, потому что поле is можно трактовать как ссылку, даже если это строка.

**Comment by ixdu** [comment]
Поскольку обсуждали уже несколько раз и все согласились с тем, что поле is : "collection" нужно, то добавил это в список задач по базе - https://github.com/Databoom/work/wiki/nitrosbasejs-todo и закрываю этот тикет.
