### ISSUE TITLE
коллекция не отображается в табличном виде

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#184]
вход в CP под 
Login	vc@NitrosBase.com    change password
Account ID	t261
Database ID	b261
Database URL	https://t261.databoom.space/api1/b261
Коллекция Car циклится при попытке показать себя в таблице. 

![image](https://cloud.githubusercontent.com/assets/13114324/14208589/de749064-f828-11e5-9b9c-12094f8c196a.png)

**Comment by ixdu** [comment]
Как оказалось причины те же, что в #198 . Просто в этом случае грид не сваливался с ошибками, а подвисал спиннер:)

**Comment by ixdu** [comment]
Теперь отображается, на тестовом, скоро будет и на основном, как оттестим как следует.
