### ISSUE TITLE
Табличное отображение при большом количестве колонок выглядит ужасно

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#185]
Можно ли сделать, чтобы колонки были приемлемой ширины, а внизу был горизонтальный скроллбар? 
![image](https://cloud.githubusercontent.com/assets/13114324/14208733/8a46c38a-f829-11e5-949f-0413958286ce.png)

**Comment by vsalnikov** [comment]
Кроме того, при большом числе колонок табличное отображение перестает работать, все зависает и не показывает данные.

**Comment by ixdu** [comment]
Да, grid встаёт колом.
Думаю что просто сделать скроллинг не выйдет, потому что kendo слишком много генерирует данных, в результате просто при большом количестве столбцов он наедается.
Буду работать над обходным путём, делая всё тот же скроллинг, но не средствами kendo.

**Comment by ixdu** [comment]
Сделал ширину столбцов по ширине заголовков.
