### ISSUE TITLE
После загрузки большого JSON-a @allobjects долго грузится, и ничего непонятно

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#186]
Надо показывать часы или что-то. Сейчас ощущение, что система не сработала. 
![image](https://cloud.githubusercontent.com/assets/13114324/14225397/46e28ef2-f8ca-11e5-8a00-1105bb78a8cb.png)

**Comment by ixdu** [comment]
Поставил полимерный spinner.

**Comment by Databoom** [comment]
Никакого spinner-а не вижу. Ведет себя теперь так: 
1. в пустом allobjects кликаю на карандаш. 
2. вставляю текст из буффера (_friends_10000_v02_nonull.json). 
3. нажимаю дискету. На экране ничего не происходит. все остается как будто в режиме редактирования. 
4. через значительное время, режим редактирования уходит, во вьюере виден текст. 
5. а еще через значительное время появилась такая надпись: "unexpected token [". Хотя файл грузился много раз, забирал я его из редактора через ctrl+A. В общем, странно.

**Comment by ixdu** [comment]
Понял, буду разбираться. Что касается токена '[' возможно дело в том, что там уже были [], а вставились объекты тоже с [] внутрь. Но это догадки, проверю. Факт в том что нужно работать, чтобы более-менее большие объёмы нормально обрабатывались.

**Comment by ixdu** [comment]
Добавил спиннер и на сохранение и на загрузку.
В общем случае json редактор виснет когда в нём хотя бы 2а мегабайта, ну то есть сильно начинает тормозить. Поэтому крайне не рекомендуется через него заливать. С другой стороны пару узких мест в обновлённом редакторе устранено, так что работает чуть быстрее.
