### ISSUE TITLE
При загрузке и во всех аналогичных ситуациях, цвет кнопки желательно поменять

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#187]
Иначе плохо видно, момент, когда загрузка завершена. 

![default](https://cloud.githubusercontent.com/assets/13114324/14225578/a4ec7188-f8d0-11e5-836e-ed1c50db68e1.PNG)
![2](https://cloud.githubusercontent.com/assets/13114324/14225580/a9d0d3ec-f8d0-11e5-96b1-bf6ff1c01ef0.PNG)

**Comment by ixdu** [comment]
Поменял на красный пока не загрузилось и зелёный, когда загрузилось. Серый как-то непригляден. Но если нужно, могу вернуть на серый)
