### ISSUE TITLE
JSON загрузился неверно

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#188]
Файл загрузился неверно. Только одни ссылки, нет объектов на которые ссылаются. 
https://dl.dropboxusercontent.com/u/21937378/_friends_10000_v02_nonull.json
То же и с 
https://dl.dropboxusercontent.com/u/21937378/friends_nonull.json
https://dl.dropboxusercontent.com/u/21937378/friends_10000.json

**Comment by ixdu** [comment]
В коллекцию загружаются только один уровень объектов, когда объект содержит другой объект, тот который содержится помещается в allobjecs. Мы только недавно обсуждали, что это нужно бы изменить, чтобы база все объекты дерева делала принадлежащими коллекции.
