### ISSUE TITLE
Неправильно расставлены таги при создании новой коллекции

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#189]
При создании новой коллекции 
1. выскакивает форма, но фокус не установлен на ввод названия
2. по enter и никак по-человечески не сделано создание коллекции после ввода названия. Почему не по tneter например? Единственно, по нажатию мыши. Это неправильно

![image](https://cloud.githubusercontent.com/assets/13114324/14228688/621ce522-f925-11e5-9dc3-20fc9640e3e2.png)

**Comment by ivanmart** [comment]
Если что, я об этом писал в #159 .

**Comment by ixdu** [comment]
Поправил. Теперь фокус на инпут, по энтеру или мышью создаётся.
