### ISSUE TITLE
При загрузке такого файла надо ли что-то делать или и так нормально? 

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#190]
https://dl.dropboxusercontent.com/u/21937378/Example%20Google%20Maps%20V02.json
При загрузке этого файла выскакивает ошибка
![image](https://cloud.githubusercontent.com/assets/13114324/14228718/59246f34-f926-11e5-9986-298244899491.png)
Возможно, это нормальная реакция, но возникает вопрос:
Человек хочет вызвать какую-то функцию в приложении для создания объекта. Он не может это сделать так?

**Comment by ixdu** [comment]
Это не json, это обычный javascript код. Да, мы не поддерживаем javascript.
И что значит так? Если он в приложении этот код вставит, скажем сделает так:
```
db.save({
    "point":new GLatLng(40.266044,-74.718479), 
    "homeTeam":"Lawrence Library",
    "awayTeam":"LUGip",
    "markerImage":"images/red.png",
    "information": "Linux users group meets second Wednesday of each month.",
    "fixture":"Wednesday 7pm",
    "capacity":"",
    "previousScore":""
});
```
То всё отработает хорошо. Если же он хочет сохранять в базе javascript, то это совершенно другая история.

**Comment by ixdu** [comment]
Лишние проверки убрал, так что если что-то не вставляется, это не корректный json.
