### ISSUE TITLE
Ошибка при загрузке файла

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#192]
https://dl.dropboxusercontent.com/u/21937378/Example%20Google%20Maps%20V03%20strings%20only.json
При загрузке файла возникает ошибка, которой не должно быть.

![image](https://cloud.githubusercontent.com/assets/13114324/14228751/a694328a-f927-11e5-9dc1-c83250aed0e4.png)

**Comment by ixdu** [comment]
Поправил, однако это не корректный json, объекты должны находиться либо в массиве либо в объекте.
Поскольку отключаю теперь клиентский парсер для проверки, то скоро будет по быстрее загружаться, но и ошибки пока что будут возвращаться без указания строк(это стандартный парсер nodejs, ищу сейчас чем заменить чтобы ошибки показывались как следует.

**Comment by ixdu** [comment]
нет, не починил, правлю дальше.

**Comment by ixdu** [comment]
Всё таки починил)

**Comment by Databoom** [comment]
Действительно, теперь не показывает, где ошибка
![image](https://cloud.githubusercontent.com/assets/13114324/14281098/b8d5ed70-fb3f-11e5-8889-3c9cbdff3ff7.png)
Тем не менее, если JSON правильный, то всасывает
