### ISSUE TITLE
При создании новой коллекции откуда-то выскакивает старое название

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#193]
Я создаю новую коллекцию, нажав + на странице collections 
Возникает не пустая форма, а почему-то с названием коллекции, которую я уже создавал. 
![image](https://cloud.githubusercontent.com/assets/13114324/14228785/9128e61a-f928-11e5-9d20-7e59c83e658a.png)

**Comment by ixdu** [comment]
Не было зачистки по cancel, сделал. Отловить появление имени коллекции, которую уже создали пока не смог, ещё понаблюдаю.

**Comment by Databoom** [comment]
Думаю, раз зачистка cancel сделана, баг можно закрыть.
