### ISSUE TITLE
прогресс бар не добегает до конца

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#194]
Надо хотя бы для приличия показать весь прогрес бар заполненным 
![image](https://cloud.githubusercontent.com/assets/13114324/14281544/6b5b1ce8-fb42-11e5-8864-33c8dd508573.png)

**Comment by ixdu** [comment]
Как оказалось баг в самом компоненте file-upload, прогрессбар добегал, но он просто у файлов с большими именами был короче имени:) Починил.
