### ISSUE TITLE
Проблемы работы с большими данными

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#196]
Похоже, что удаление сделано через JavaScript. При удалении большой коллекции в разделе collections, курсор начинает мерцать и ничего невозможно делать.

**Comment by ixdu** [comment]
Хм, через javascript сделан редактор json, там да, надо доработать чтобы с большими объёмами справлялось.
А вот это, должен быть где-то явный баг.

**Comment by Databoom** [comment]
Оказалось, не только удаление. Вообще, после загрузки большого JSON (_friends_10000_v02_nonull.json) в allobjects
1. загруженный JSON долго не показывается в allobjects. А в остальном поведение как обычно, поэтому паническое ощущение, что sjon не загрузился. 
2. Через некоторое время данные появляются в allobjects - после этого CP становится жутко тормознутой. Причем, даже если я пытаюсь смотреть маленькие коллекции, все грузится очень медленно. 
3. Через некоторое время (ощутимое) все устаканивается и работает нормально. 
4. Но стоит мне что-то реальное сделать (например, удалить большую коллекцию) - опять все замедляется больше чем на минуту. Однажды даже сработало сообщение "Приложение не отвечает. Закрыть? Подождать?"
Думаю, что это будет людей раздражать. 
При том, что это в общем небольшой файл 10 тыс объектов, 6.5 мб.

**Comment by ixdu** [comment]
Проверил удаление, там всё работает и ничего не менялось. Проверил заливку-удаление тоже всё ок.
Однако да, при работе с объёмами больше 4х мегабайт да, интерфейс ведёт себя неадекватно. Это даже меня раздражает, не то что клиентов, их это в ступор заведёт.
Поэтому думаю этот тикет нужно переименовать в "Проблемы работы с большими данными".
И писать сюда все связанные с этим проблемы.
Как минимум можно сказать, что json редактор тоже плохо переваривает большие объёмы и нужно его перерабатывать, добавлять в него что-то вроде pagination. 
Грид теоретически способен работать с большими данными, потому что использует виртуальный скроллинг с подгрузкой данных порциями. Но нужно это хорошенько протестировать.
Из срочного по этой теме очевидно нужно сделать в библиотеке работу с json без его разбора. Частично я это уже реализовал, как доделаю и интегрирую в админку будет по легче.

**Comment by ixdu** [comment]
Интегрировал доработанную библиотеку, сделал pagination для json редактора и больше фризов интерфейса не наблюдаю. Выставил пока размер страницы в 300 объектов, грузит приемлемо.
Также переработал у json редактора сохрание, теперь не портит ссылки, использует put для обновления и delete для удаления как и следует.

**Comment by ixdu** [comment]
Убрал несколько лишних запросов и жуткий способ определения столбцов, грузящий мегабайты из базы. Стало похоже совсем без тормозов, но надо ещё понаблюдать.
Пробовать можно на тестовом сервере https://databoom.space:8001
