### ISSUE TITLE
Комплексная ошибка

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#197]
1. удаляю приличных размеров коллекцию (Friends1)
2. создаю одноименную коллекцию. Коллекция не создается, при нажатии F5 выскакивает ошибка: 

![image](https://cloud.githubusercontent.com/assets/13114324/14281987/e4a4f522-fb44-11e5-903b-7ce114926679.png)

**Comment by ixdu** [comment]
C удалением и добавлением коллекций это не связано. Было полное обновление работы с маршрутами, чтобы стало возможно открывать любую ссылку в новом окне, а также для того чтобы некоторые ссылки в принципе заработали. На решение двух багов, вылез один, мешающий обновлению страницы.
Починил.
