### ISSUE TITLE
Grid не работает, если поля в объектах не являются корректными javascript идентификаторами(то есть содержат пробелы или иные недопустимые символы)

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#198]
Вот объекты
![image](https://cloud.githubusercontent.com/assets/13114324/14285631/fc9db3ac-fb54-11e5-8a1b-90329854bbef.png)
А вот их нету
![image](https://cloud.githubusercontent.com/assets/13114324/14285663/1bd0ee6a-fb55-11e5-96df-b8187540a3bc.png)
А вот они есть вне CP 
![image](https://cloud.githubusercontent.com/assets/13114324/14285700/3421a806-fb55-11e5-9ef6-90ed593b54de.png)

**Comment by ixdu** [comment]
Данные грузятся, запрос отрабатывает, в json режиме данные видно. kendo же сваливается отчего-то, выясняю.

**Comment by ixdu** [comment]
Сваливается вот от этого:
```
"Year of birth": "1998",
```
Вот поэтому там правила наименования столбцов, в добавлении столбцов. Название поля не может иметь пробелов, начинаться с цифр и прочего.

С другой стороны раз существуют такие json, которые имеют вот такую вот структуру, но нужно сделать так чтобы они отображались в grid. Посмотрю что можно сделать.

**Comment by Databoom** [comment]
Да в общем, делать ничего не надо, надо чтобы как-то это все диагностировалось. 
Если это сложно сделать у нас, может быть рекомендовать людям сервисы, которые проверяют JSON-ы на правильность?

**Comment by ixdu** [comment]
JSON верный, потому что в кавычках может содержаться любая строка. И в базе у нас он хранится правильно и json режиме он также отображается и его можно редактировать.

А вот grid, не умеет с таким json работать. Лучше его научить. Вопрос в том можно ли относительно легко научить kendo этому или проще выкинуть kendo и написать замену с учётом других тикетов, которые также в kendo реализуются очень сложно. Это я и выясняю.

**Comment by ixdu** [comment]
Способ как выкрутится нашёл, буду делать.

**Comment by ixdu** [comment]
Сделано, названием стобцов может быть любая строка.
