### ISSUE TITLE
Не работает перевод в другую коллекцию

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#199]
1. Объект принадлежит одной коллекции
2. в Grid view пытаюсь перевести в другую коллекцию
3. Выбираю коллекцию, жму Apply, 
![image](https://cloud.githubusercontent.com/assets/13114324/14286503/e7da8c1c-fb57-11e5-8684-aea9bd3efa03.png)
****
4. объект остается в прежней коллекции. 
![image](https://cloud.githubusercontent.com/assets/13114324/14286534/fdec2f7e-fb57-11e5-9260-7c6893619c98.png)

**Comment by ixdu** [comment]
Отвалилось что-то в серверной логике, немного изменил запрос, добавление в коллекцию теперь работает. Однако удаление из - нет, будем дальше искать.

**Comment by ixdu** [comment]
И удаление.работает, но только если у объекта есть хотя бы одно поле кроме id)

**Comment by ixdu** [comment]
То что у пустых объектов нельзя менять ссылки, то есть в нашем случае принадлежность коллекциям, так задумано.
