### ISSUE TITLE
Появились объекты принадлежащие коллекции allobjects

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#203]
Так быть не должно, allobjects - это же псевдоколлекция!
![image](https://cloud.githubusercontent.com/assets/13114324/14329337/9db5c8e4-fc43-11e5-80ef-1dd601c1d311.png)

**Comment by Databoom** [comment]
- Первоначально я гружу json такой 
[Movies01_V02.json.txt](https://github.com/Databoom/work/files/207150/Movies01_V02.json.txt)
Результат нормальный, аномалий нет. 
![image](https://cloud.githubusercontent.com/assets/13114324/14329483/302adba6-fc44-11e5-9b16-9dcc187fe880.png)
- Создаю коллекцию Movies
- Иду в allobjects, в режиме редактирования всем фильмам проставляю в JSON View
    "collections": [
      {
        "id": "Movies"
      }
    ]
- нажимаю дискету, пишет что успешно сохранено. 
- иду в коллекцию Movies - она пустая
- иду назад в allobjects - вижу что объекты, которым я проставил коллекцию Movies там и остались, а остальным присвоилась коллекция allobjects

**Comment by ixdu** [comment]
Поправил, был баг в серверной части, по факту allobjects не была псевдоколлецией и заливка в неё приводила к присваиванию этой коллекции объектов, никому не принадлежащих. То есть точно также, как бы происходило с любой другой коллекцией.
Проделал вышеописанное с фильмами, только не создавал коллекцию мувис, всё работает.
