### ISSUE TITLE
Коллекция Movies не показывает содержимое

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#205]
1. загрузил файл Movies JSON (приложен)
[Movies01_V02.json.txt](https://github.com/Databoom/work/files/208134/Movies01_V02.json.txt)
2. руками в allobjects вставил 
, "collections": [
  {
    "id": "Movies"
  }
]
3. нажал дискету. 
В меню появилас коллекция Movies, 
В allobjects объекты приписались коллекции Movies
![image](https://cloud.githubusercontent.com/assets/13114324/14347628/cce6fcbe-fcc0-11e5-94ae-17ef672bee30.png)

Но в коллекции Movies - пусто. 
![image](https://cloud.githubusercontent.com/assets/13114324/14347654/e43f3930-fcc0-11e5-9644-e12a30ddf616.png)

**Comment by ixdu** [comment]
Это тоже самое, что #198

**Comment by ixdu** [comment]
Починено на тестовом.
