### ISSUE TITLE
Не сохраняет JSON

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#206]
1. Создаю коллекцию odata1
2. захожу в нее в JSON view в режим редактирования
3. делаю paste такой json
{"@odata.context":"http://services.odata.org/V4/(S(de4ovaq41puf0u1d4bynwhqp))/TripPinServiceRW/$metadata","value":[{"name":"Photos","kind":"EntitySet","url":"Photos"},{"name":"People","kind":"EntitySet","url":"People"},{"name":"Airlines","kind":"EntitySet","url":"Airlines"},{"name":"Airports","kind":"EntitySet","url":"Airports"},{"name":"Me","kind":"Singleton","url":"Me"},{"name":"GetNearestAirport","kind":"FunctionImport","url":"GetNearestAirport"}]}
4. жму сохранить - ничего не происходит. 
5. выхожу из коллекции, возвращаюсь - коллекция пустая.

**Comment by ixdu** [comment]
Неплохо бы писать где) Проверил на тестовом не сохраняет, да. Нашёл ещё пару нюансов, сегодня поправлю. Потому оно и на тестовом, потому что не только переписана логика сохранения, загрузки и работы с данными, но и библиотека уже используется обновлённая:)
На самом деле сохраняет, если добавить вокруг [], но всё равно поправлю.

**Comment by ixdu** [comment]
теперь сохраняет.

**Comment by ixdu** [comment]
То есть это на основном происходит? Ничего такого не смог смоделировать. Понаблюдаю.

**Comment by Databoom** [comment]
> На самом деле сохраняет, если добавить вокруг []
Это тоже не работает

**Comment by ixdu** [comment]
Проверил и на основном и на тестовом сервер(а сейчас на основном тоже новая логика сохранения) - всё работает. Как в отдельную коллекцию сохраняет, так и в allobjects/

**Comment by ixdu** [comment]
Обновил редактор на основном. Сохраняет, как в allobjects так и в любую коллекцию.
