### ISSUE TITLE
Не удаляет из Allobjects

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#207]
Загрузил большой объем в базу в allobjects, коллекции насоздавал. Это все в 	t277
зашел в allobjects, в json view в режиме редактирования выделил все и удалил. 
Не удалилось ничего и никакой диагностики. 
Если так нельзя - то надо выдавать сообщение.

**Comment by ixdu** [comment]
Нет, так можно, но скорее всего из-за большого объёма, если это основной сервер, а скорее всего он раз можно всё выделить, просто что-то не отрабатывает.  На малых объёмах сейчас проверил всё работает. На больших я вообще адекватно проверить не могу, виснет интерфейс.
