### ISSUE TITLE
один и тот же файл через cut-paste грузится, через upload - нет

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#21]
Вот этот файл я выгрузил из базы с помощью cut/paste из collection JSON view. 
Потом я его немного модифицировал, заведомо не портя синтаксис и пытался загрузить через upload - ошибка. 
Загрузил с помощью cut/paste из collection JSON view - успешно
[db.json.txt](https://github.com/Databoom/work/files/101232/db.json.txt)

**Comment by ixdu** [comment]
Проблема решена, баг этот уже был описан раньше под номером 5.
