### ISSUE TITLE
Загрузка приложения требует ctrl + F5

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#210]
Есть приложение - HTML файл, реализующее блог
[index.html.txt](https://github.com/Databoom/work/files/216795/index.html.txt)
при запуске все грузится, кроме самих постов. 
Для того чтобы отобразились посты приходится нажимать ctrl + F5
Программист проверял, говорит, что при загрузке возникают кривые запросы. 
![img_11042016_154221](https://cloud.githubusercontent.com/assets/13114324/14489760/ae43931a-0177-11e6-80a0-6d1719329035.png)
Надо разобраться, в чем дело.

**Comment by ixdu** [comment]
больше не требует же)
