### ISSUE TITLE
странное поведение при изменении ширины колонок в grid view

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#211]
при изменении ширины колонок, например коллекция car_bid колонка values и другие, граница колонки отпрыгивает и потом двигается отдельно от курсора. В общем, в результате ширину колонки поменять удается, но как-то не прямым путем и намного дольше.

**Comment by ixdu** [comment]
Посмотрю что можно сделать, но похоже это такой лаг при переходе от авторазмера(когда колонок мало грид автоматически их ресазит чтобы они больше занимали) к регулируемому.

**Comment by ixdu** [comment]
Да, специфическое поведение, когда все столбцы имеют заданную ширину и грид их пытается растянуть.
