### ISSUE TITLE
Если в столбце коллекции есть пустые значения, то при клике на заголовок, зацикливается

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#217]
Коллекция Movies имеет столбцы с пустыми значениями. 
При клике в заголовок такого столбца вместо сортировки возникают бесконечные часы. 
С остальными столбцами все нормально.

**Comment by ixdu** [comment]
Сделал чтобы в случае ошибок всплывала информация о ошибке и потом перезагружался грид с дефолтными настройками. Однако проблему с ордер это не решает, о ней Сергея оповестил.

**Comment by ixdu** [comment]
Изменён запрос, теперь база не падает, сортировка работает. Но если объект значения не имеет, его не будет в выдаче. Как только починят работу order c несуществующими полями в базе, такие объекты будут в выдаче.

**Comment by ixdu** [comment]
Возникли дополнительные осложнения, так что всё таки ждём исправление в базе.

**Comment by ixdu** [comment]
Ошибка найдена и устранена.
