### ISSUE TITLE
появились 2 одноименных столбца

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#218]
![image](https://cloud.githubusercontent.com/assets/13114324/14561040/505617cc-031c-11e6-85b1-55b3fa41c070.png)
В принципе понятно, откуда это идет. 
Там в JSON была ошибка. в одном объекте было написано так: 
"Year\r\n" : "1999",
в других без escape символов. 
"Year" : "1999",
Ты убрал escape символы, а столбцы не слил. 
Может быть не править такие случаи? Оставить на совести пользователя? 
или при загрузке ругаться, если это надо?

**Comment by ixdu** [comment]
Править это нельзя, потому что это может быть и не ошибка. То есть в данном случае да, это вышел косяк такой. Но в другом случае человек мог так и задумать.
С точки зрения грида, да и любого другого приложения это разные столбцы. Думаю здесь не стоит что-то менять.
Кроме того, даже если сделать такое объединение, то в какое поле грид должен записывать изменения? Грид сам должен решать? Как-то это слишком мне кажется.

**Comment by Databoom** [comment]
согласен. Тогда надо вернуть Escape символы

**Comment by ixdu** [comment]
А они и никуда и не девались, это видно в json режиме. Иначе бы это не были две колонки. Проблема была в том, что символы неразескейпивались, когда приходили. То есть когда сохраняются в базу они эскейпятся, а потом идут обратно и неразескейпиваются. Получаются что при каждой записи в базе всё больше слешей. 
Здесь просто надо понимать что такое escape символы и что такое json. В json данные хранятся, то как они хранятся не значит что они также отображаются. Поэтому например "Year\n" в json будет выглядеть как Year в grid. Это потому, что когда json обрабатывается, никаких espace последовательностей в строке не стаёт, на то они и escape последовательности.

**Comment by Databoom** [comment]
Тогда проблема больше чем я думал. 
Мне это сильно не нравится. 
Если в JSON название "Year\n", то и в гриде должно быть "Year\n". Не понимаю
