### ISSUE TITLE
в Allobjects Grid View путаница в представлении несуществующих полей для разных объектов

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#219]
На картинке: 
Для полей Year и Place of Birth несуществующее поле представляется пустым. 
Для полей Budget и Year of Birth - null
Для ссылочных полей - идет сплошняком More, даже для несуществующих полей. 

![image](https://cloud.githubusercontent.com/assets/13114324/14625137/1eb15a86-05e9-11e6-9e97-0a42600d27f8.png)

**Comment by ixdu** [comment]
Все несуществующие поля теперь отображаются как undef, но при клике редактируются как раньше.
