### ISSUE TITLE
не вкачивается JSON полностью

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#220]
Movies01_V03.json вкачивается только 1й объект. 

Файл Movies01_V03_brackets.json вкачивается, поскольку это легальный JSON
Файл Movies01_V03.json представляет собой тот же файл, только убраны внешние [].
По идее, возможно, его не надо вкачивать поскольку это неправильный JSON, но тогда надо на него ругаться, а не вкачивать один объект. 

Я бы предпочел, чтобы файл вкачивался, поскольку это последовательность объектов. Но можно обсудить. 

[Movies01_V03_brackets.json.txt](https://github.com/Databoom/work/files/225129/Movies01_V03_brackets.json.txt)
[Movies01_V03.json.txt](https://github.com/Databoom/work/files/225128/Movies01_V03.json.txt)

**Comment by ixdu** [comment]
Сделал для вкачивания в коллекцию, на очереди для вкачивания в разделе database.

**Comment by ixdu** [comment]
Сделано для database.
