### ISSUE TITLE
после cleanup database сообщение не уходит

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#221]
Чисто косметический баг. 
1. жму cleanup database. Выскакивает сообщение
2. если жму в пустое поле, то сообщение исчезает. Но если жму upload database - то сообщение не уходит, а второе ложится поверх

![image](https://cloud.githubusercontent.com/assets/13114324/14628983/9b62ebae-060b-11e6-971e-4d9b02d4488f.png)

**Comment by ixdu** [comment]
переделал открытие всех диалогов, теперь только по одному диалогу за раз.
