### ISSUE TITLE
Перепутались поля

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#222]
Через приложение
[index — копия (6).html.txt](https://github.com/Databoom/work/files/225309/index.6.html.txt)
создал пост в пустом блоге
[Demo Blog.docx](https://github.com/Databoom/work/files/225310/Demo.Blog.docx)
Взял 1-й контекст, вставил картинку, опубликовал. Картинка пропала, остальной текст остался. 
В CP посмотрел на данные, и вот что увидел. 
![image](https://cloud.githubusercontent.com/assets/13114324/14629213/99d1d0d2-060d-11e6-92b6-8382a8c8f73d.png)

**Comment by Databoom** [comment]
Проверил еще раз - дело в картинке. Я ее через copy-paste вставил из Worda, нажал enter, чтобы перейти на другую строку и олубликовал

**Comment by ixdu** [comment]
Ну там не конкретно в картинке дело, а в том что вставляется в строку html код, а потом грид его отображает как html, а не как строку. В итоге сбивается вся разметка. Поправил.
