### ISSUE TITLE
Если человек не залогинился, ему на каждой странице сайта должно показываться "Sign up for free"

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#226]
Можно показывать в верхней панели. 
Сейчас это не показывается на страницах doc, samples

**Comment by ixdu** [comment]
Сделал чтобы показывалось.

**Comment by Databoom** [comment]
не показывается на страницах doc, samples, на странице blog цвет кнопки другой
![image](https://cloud.githubusercontent.com/assets/13114324/15011839/b58d9496-11fc-11e6-9b5f-94be331bb6d5.png)

**Comment by ixdu** [comment]
Только что проверил, если не залогинен - показывается на страницах doc и samples. Если не залогинен - не показывается. 
Что до блога, там шапка со старого сайта используется пока, без полимера, скорректирую цвет.

**Comment by ixdu** [comment]
цвет поправил
