### ISSUE TITLE
Если набрать http://databoom.space/samples выскакивает пустая страница

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#228]
Хотя при этом URL трансформируется вроде бы в правильный, но содержимое отсутствует
![image](https://cloud.githubusercontent.com/assets/13114324/14733127/42d264c8-0869-11e6-8eea-73e401a7d17b.png)

**Comment by ixdu** [comment]
Да, эти url правильные, но не были привязки ни одной страницы.
Такая же история у docs, сделал у обоих переход на about и what-is-databoom соответственно.

**Comment by Databoom** [comment]
переход не работает, теперь выскакивает ошибка
![image](https://cloud.githubusercontent.com/assets/13114324/14782028/23575666-0aef-11e6-94ea-f3f641309f0b.png)

**Comment by ixdu** [comment]
Всё правильно, так и должно быть. А где такая ссылка где просто databoom.space/samples? Если она где-то есть, её надо поправить. Выше я неправильно прочёл, нет databoom.space/samples это неправильный запрос, правильный - databoom.space/samples.html. И по не правильному и должен быть not found.
