### ISSUE TITLE
После добавления коллекции вне CP она не появилась в меню

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#229]
В аккаунте t334/avssn123
Добавил комментарий вне CP, 
как я помню, коллекции comments не было в базе сначала. 
зашел в CP - такая картина. 
![image](https://cloud.githubusercontent.com/assets/13114324/14761221/ce7aa590-0962-11e6-9244-d6cef7cb4e4a.png)

**Comment by ixdu** [comment]
Добавил обновление меню при его открытии, то есть переходе из другого меню.
