### ISSUE TITLE
файлы лучше показывать в таблице

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#230]
Тогда можно было бы показывать
1. имя
2. размер
3. дату загрузки
4. URL по которому его можно достать (важно)

**Comment by ixdu** [comment]
Сделал отображение в таблице. Размер и дата загрузки также отображаются.

**Comment by Databoom** [comment]
Пока вижу, что если у меня нет файлов, то нет способа добавить файл!

**Comment by ixdu** [comment]
Поправил.
