### ISSUE TITLE
После присваивания объекта коллекции в Grid View ширины колонок сбрасываются

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#233]
Я делаю удобную мне ширину колонок
![image](https://cloud.githubusercontent.com/assets/13114324/14860854/5a4371da-0cb3-11e6-8428-35c5bea025a9.png)
объект вношу в коллекцию Actors - все ширины сбрасываются
![image](https://cloud.githubusercontent.com/assets/13114324/14860867/6c31c2de-0cb3-11e6-8e23-fedb9df6b17e.png)

**Comment by ixdu** [comment]
Починил
