### ISSUE TITLE
Если я внес объект в коллекцию - я не могу его оттуда убрать

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#234]
Объект Name: Sam Mendes внесен в коллекцию Actors 
![image](https://cloud.githubusercontent.com/assets/13114324/14860991/ecf55e12-0cb3-11e6-8845-26f8ca0562fc.png)
Я пытаюсь его убрать из коллекции расчекнув чекбокс
![image](https://cloud.githubusercontent.com/assets/13114324/14861015/0a1d4040-0cb4-11e6-982a-7b12df54e332.png)
ничего не получается. Объект остается в коллекции.

**Comment by Databoom** [comment]
Более того, я даже из JSON не могу убрать. Перехожу в JSON, убираю у Sam Mendes коллекцию - сохраняю - все возвращается.

**Comment by ixdu** [comment]
Насчёт json режима, сейчас проверил, работает, по крайней мере не могу воспроизвести. И удалял из массива объект, и полностью поле. Может и должно не работать удаление в json режиме, когда находишься в коллекции, потому что происходит сохранение в коллекцию. Но когда в allobjects должно работать.
Грид поправил, из грида теперь работает.
