### ISSUE TITLE
Удаление объекта из коллекции

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#235]
Неоднозначность такая возникает: 
я в Grid View нажимаю крестик напротив объекта. У меня возникает выбор:
- удалить из всех коллекций - тогда он однозначно удалится из базы
- удалить из этой коллекции. Тогда возникает разное поведение в зависимости от конфигурации данных. 
Если объект содержится только в этой коллекции - то он уйдет совсем. 
Если же в нескольких - то останется в базе. 
А поскольку, система никак не предупреждает меня, что удалив из этой коллекции я потеряю объект, а не только его вхождение, то может оказаться, что я потерял объект того не желая. 

Надо что-то придумать. 

Возможно, надо предупреждать, что сейчас будет удален объект из базы, а не только из коллекции.

**Comment by ixdu** [comment]
Ну тут вариантов немного, либо предупреждать что удалится совсем(вернее наверное это) либо не удалять его в любом случае, а только убирать из коллекции. Для одиночного удаления стоит сделать предупреждение, что удаляется, это логично.
Однако на подходе выделение объектов и удаление сразу группы выделенных объектов, в таком случае диалоги подтверждения будут сыпаться прямо как при удалении защищённых файлов на файловой системе:) Наверное это тоже нормально.

**Comment by ixdu** [comment]
Добавил диалог, предупреждает если собирается удалять полностью.

**Comment by Databoom** [comment]
Реализация нормальная, пара уточнений: 
1. Сообщение лучше такое: 
You are going to remove the object completely. Are you sure?
2. Можно то же сообщение повесить и на случай удаления из всех коллекций. Вдруг я случайно нажал - тогда я потеряю весь объект. Лучше спросить.

**Comment by ixdu** [comment]
Сделано.
