### ISSUE TITLE
В lone objects показываются коллекции

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#236]
1. Загрузил файл Movies.json - все объекты вне коллекций. 
2. Создал коллекцию Actrors
3. Открываю loneobjects - вижу в ней объект Movies, который по-видимому, коллекция. 
![image](https://cloud.githubusercontent.com/assets/13114324/14909631/989fed82-0dee-11e6-9e76-106a8a8eba1e.png)

**Comment by ixdu** [comment]
Ну во-первых, а разве не должны показываться здесь коллекции? Где-то же их нужно показывать, это же всё таки объекты. Во-вторых, пока база не помечает объекты коллекций явно, отфильтровать от коллекций, которые ничего не содержат невозможно однозначно, потому что такие объекты ничем не отличаются от других.
Можно отфильтровать только от коллекций, которые содержат объекты, как это делается в allobjects.

**Comment by ixdu** [comment]
Добавил зачистку как для allobjects, однако она не удаляет просто объекты, на которые никто не ссылается.
