### ISSUE TITLE
запрос не работает

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#237]
1. Закачал movies.json
[Movies01_V03.json.txt](https://github.com/Databoom/work/files/241896/Movies01_V03.json.txt)
2. Перекинул фильмы в коллекцию Movies
3. задал запрос https://t277.databoom.space/api1/b277/collections/Movies?filter=(Budget%20gt%2020000000)
Результат - все 3 фильма на экране, ходя должен остаться один. 
![image](https://cloud.githubusercontent.com/assets/13114324/14910056/ca17c278-0df2-11e6-8a6d-5d7ef4f50445.png)
Похоже, проблема в базе, поскольку не работает также и запуск запроса из адресной строки
![image](https://cloud.githubusercontent.com/assets/13114324/14910079/f9976da0-0df2-11e6-8387-b532ecff18a7.png)

**Comment by Databoom** [comment]
Похоже, вообще запросы не работают. Мне не удается запустить с фильтром ни одним.

**Comment by ixdu** [comment]
Потому что filter должен начинаться с $, и то есть запрос выглядит как https://t277.databoom.space/api1/b277/collections/Movies?$filter=(Budget%20gt%2020000000) и всё работает
