### ISSUE TITLE
с ширинами колонок в loneobjects что-то не то

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#238]
колонка Year of Birth шире чем нужно, в то же время, колонка ID уже чем нужно. 

![image](https://cloud.githubusercontent.com/assets/13114324/15011545/160dcdba-11fb-11e6-91a9-3c6891055a59.png)

**Comment by ixdu** [comment]
Ширина зависит от заголовка, и если сумма заголовков меньше доступного пространства - раскидывается на все пропорционально. И это не особенность loneobjects, это в принципе так сейчас рисуется грид.
Если сделать просчёт по содержимому, то возможно сильное замедление прорисовки грида, потому что нужно все поля проверять. Посмотрю, можно ли сделать это более-менее оптимально.

**Comment by ixdu** [comment]
Ну вот, теперь у нас полностью собственный алгоритм распределения ширин столбцов.
Сделал чтобы учитывал содержимое. Теперь если есть лишнее место, оно раскидывается по тем столбцам, у кого не влезает содержимое до тех пор пока не влезет или пока не кончится лишнее место.
