### ISSUE TITLE
в loneobjects не хватает колонки Collections

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#239]
Она должна быть пустая, но с помощью нее я могу присваивать коллекции объектам. 

![image](https://cloud.githubusercontent.com/assets/13114324/15011656/bf561f58-11fb-11e6-9ef5-f77195714999.png)

**Comment by ixdu** [comment]
Сделаю, но её можно создать как обычную колонку, даже тип указывать не нужно, выберется правильный сам.

**Comment by ixdu** [comment]
Сделано.
