### ISSUE TITLE
в любом grid view не хватает колонки Collections

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#240]
1. Вкачиваю файл 
[Movies01_V03.json.txt](https://github.com/Databoom/work/files/250632/Movies01_V03.json.txt)
2. Создаю коллекцию Directors
2. Иду в allobjects или loneobjects, в Grid View
3. В любой строчке, например, Forrest Gump в колонке Directors кликаю more - открывается строчка Robert Zemeckis
4. Хочу поместить Robert Zemeckis в коллекцию Directors - не могу, нет колонки Collections.

**Comment by ixdu** [comment]
Думал будет достаточно создания такой колонки, она создаётся легко, даже тип указывать не надо. Значит сделаю для любого грида по дефолту эту колноку.

**Comment by ixdu** [comment]
Сделал для любого.
