### ISSUE TITLE
Иконки upload/download коллекции надо куда-то пристроить

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#242]
Действия: 
1. Загружаю коллекцию 
[Movies01_V05 — копия.json.txt](https://github.com/Databoom/work/files/251581/Movies01_V05.json.txt)
2. иду в allobjects, в grid view
3. в первом попавшемся фильме, в колонке Directors кликаю в more
Результат:
![image](https://cloud.githubusercontent.com/assets/13114324/15065294/ee1a38da-1366-11e6-81bc-10876ed582d4.png)
1. Радиобатоны и кнопки upload/download как-то криво расположены относительно наименования. 
2. Всплывающие подсказки на upload/download undefined
Возможные решения: 
1. Возможно стоит радиобатоны и кнопки upload/download поместить в один ряд и расположить это все в той же строке, где кнопки add column, и т.д. 
2. Возможно стоит убрать upload/download кнопки, а внести их функционал под actions. Это было бы логично?

**Comment by ixdu** [comment]
1.Расположить в один ряд можно, но логика тут такова, что кнопки upload/download и перключение grid/json относится к коллекции, а кнопки сверху редактора - относятся к редактору, но это не существенно. Посмотрим как лучше будет так и сделаем.
2.Убрать в actions не логично, потому что actions это действия над выделенными строчками, то  есть в дальнейшем там расположатся например присвоение коллекции сразу группе объектов. 

А в целом однозначно это проблема та же что в #243, поиграюсь с вариантами и выберем что больше подходит.

**Comment by ixdu** [comment]
Сделал в виде navbar, хотя стиль navbar не используется. 
1. Cтрока названия коллекции или путь на прежнем месте. 
2. Справа вместо полимерных радиобатонов сделаны pills, кнопки переключатели режимов grid и json.
3. Download the collection и upload into collection убраны в меню. Кнопка меню в виде menu-hamburger добавлена после переключателей режимов. Так мы сможем в дальнейшем добавлять новые действия над коллекцией в это меню не разбивая ничего.
