### ISSUE TITLE
Уменьшить название коллекции

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#243]
![image](https://cloud.githubusercontent.com/assets/13114324/15065406/f7622816-1367-11e6-8a4e-6c9ba659b8f4.png)
Возможно, надо решать вместе с issue #242. Я бы так реорганизовал это пространство: 
![untitled-1](https://cloud.githubusercontent.com/assets/13114324/15065488/dbe5871c-1368-11e6-8e92-59fd5ee04648.jpg)

**Comment by ixdu** [comment]
Сделал уменьшение в зависимости от длины строки, но пока не сильно интеллектуально, 3и размера сделал. Для обычных коллекций выглядит как раньше, для путей с allobjects показывается меньше, чтобы уместить.
