### ISSUE TITLE
Однажды выделенная строка не развыделяется никаким образом

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#245]
1. Свирепый оранжевый цвет - абсолютно не в цветовой гамме дизайна
2. Куда ни кликай - выделение не пропадает. 

![image](https://cloud.githubusercontent.com/assets/13114324/15065649/8108c94c-136a-11e6-9b46-5270ffb23ba4.png)

**Comment by ixdu** [comment]
Сделал чтобы пропадало выделение, если кликнуть за пределы грида.
