### ISSUE TITLE
В разделе Database иконки не выровнены. 

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#25]
http://protodesk.cloudapp.net/admin.html#!/database 
Иконки гуляют вправо-влево.

**Comment by ixdu** [comment]
баг 18.

**Comment by Databoom** [comment]
иконки как гуляли - так и гуляют

**Comment by ixdu** [comment]
Да, только зачем два бага на одну проблему:)

**Comment by ixdu** [comment]
Поправил, кстати то что они гуляли, это я их правил, дурацкий file-upload толком не подхватывает стили:)
