### ISSUE TITLE
ссылочное поле, даже если оно udefined, ссылается куда-то

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#250]
в базе b277 таблица 
http://databoom.space/cpanel.html#!/collections/Actors
в Grid View можно кликнуть в поле Relatives даже если оно undefined, и получить ссылку куда-то

**Comment by ixdu** [comment]
Хм, смысле получить? Это механизм добавления ссылок, если нельзя будет кликнуть, то нельзя будет и добавить. При этом ничего не добавляется и не получается, пока не будет добавлена хотя бы одна ссылка. Логика подобна тому, как задаётся обычное значение поля, когда оно не определено - кликнуть и задать.
Если нужно другое поведение, нужно обдумать.
