### ISSUE TITLE
невозможно выделить несколько строк в Grid View

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#251]

**Comment by ixdu** [comment]
Здесь бы неплохо уточнить, как не получается выделить? 

Могу точно сказать что выделение работает только мышью, с клавиатуры не работает, возможно ли делать это с клавиатуры не знаю, надо будет посмотреть что там кендо умеет в этом смысле. 

Также есть нюанс при выделении мышью, сделано так, что выделять надо начинать на какой-нибудь строке. Если же попробовать выделять с пустой строки, то есть того места в гриде где нет строки, то выделение работает браузерное, как текста, а не выделение строк грида. Возможно это поведение можно поправить, надо посмотреть.

Если речь о чём-то другом, то неплохо бы пример, потому что воспроизвести не смог.

**Comment by Databoom** [comment]
В общем, нельзя выделить как обычно через ctrl + мышь. 
Единственно, можно выделить только обведя мышью диапазон. 
Если это сложно исправить - то пусть остается так.

**Comment by ixdu** [comment]
Понял, не работает ctrl + клик мыши, потому как если ctrl + обводить мышью то работает. Такое вот странное поведение kendo, посмотрю что с этим можно сделать.

**Comment by ixdu** [comment]
Там вообще были проблемы с выделением кликом, починено.
