### ISSUE TITLE
Проблема при сохранении пустого массива в Json View

### ISSUE THREAD

**Issue by art-grig** [Databoom/work#252]
Игнорирует добавление пустого массива в json view, например, после добавления поля
nodes : []
просто ничего не происходит

**Comment by ixdu** [comment]
Это в принципе так, то есть это не особенность json view, а особенность того как база добавляет ссылки. Пустой массив не имеет ссылок, а значит ничего не добавляется и поле не создаётся. Работает как буд-то вот такое добавляется: nodes : undefined
Тут нужно разбираться нужно ли менять такое поведение или просто документировать такие места.

**Comment by Databoom** [comment]
Лучше документировать.
