### ISSUE TITLE
Колонка collections гуляет

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#257]
Без моего участия в Grid View колонка collections появляется в разных местах. 
![image](https://cloud.githubusercontent.com/assets/13114324/15513804/e44c60d0-21ee-11e6-9de0-89a0246902e9.png)
![image](https://cloud.githubusercontent.com/assets/13114324/15513840/fd9b3840-21ee-11e6-8fd5-229b73cc966a.png)
![image](https://cloud.githubusercontent.com/assets/13114324/15514701/07fbe844-21f3-11e6-91c8-ad569c317947.png)
В основном как правило колонка Collections идет 2й после ID, но бывают сюрпризы.

**Comment by ixdu** [comment]
Ну там было так, если ни один объект не принадлежит ни одной коллекции, например в loneobjects, то collections колонка создаётся и находится на втором месте.
Ежеле у объектов есть свойство collections, то как получится, то есть зависит от того в каком месте это свойство расположено в объектах.
Сделал чтобы всегда на втором месте располагалось.

**Comment by Databoom** [comment]
Все равно гуляет
![image](https://cloud.githubusercontent.com/assets/13114324/15519070/64340ec4-2208-11e6-93c0-e1c9bc7d65d7.png)
![image](https://cloud.githubusercontent.com/assets/13114324/15519082/735e5d82-2208-11e6-948a-81fc9e823a16.png)

**Comment by Databoom** [comment]
Починилась как-то
