### ISSUE TITLE
Нужен отдельный раздел для работы с файлами. 

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#26]
Возможно, надо отложить на потом, но надо сделать отдельный раздел для работы с файлами. В идеале должно быть с файловым менеджером, который выглядит похоже на все файловые менеджеры, с возможностью download, upload, delete файлов. Надо ли создавать папки - не уверен.

**Comment by ixdu** [comment]
Нужна и соответствующая  функциональной в библиотеке. На данный момент работа с файлами, если я всё хорошо понял по тому что вижу в базе и библиотеке не более чем прототип.

**Comment by ixdu** [comment]
На сегодня, у серверной части нет таких обычных возможностей как rename, delete и это только то что сразу приходит на ум. 
Моё мнение: нужно базовое api сначала перепроектировать, потом браться за это. Но с другой стороны, не вижу ничего сложного реализовать недостающие серверные воможности и сделать файлменеджер.

**Comment by ixdu** [comment]
Сделан раздел файлов, на тестовом запущен, работает заливка, удаление, переименование файлов.

**Comment by ixdu** [comment]
перевёл на основной.

**Comment by Databoom** [comment]
что-то не вижу никакого раздела работы с файлами
