### ISSUE TITLE
При удалении коллекций из базы, они не уходят из меню

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#27]
1. зашел в Collection @allobjects JSON view
2. выделил все и удалил из окна. 
3. нажал сохранить в базе
4. В списке коллекций в меню должна была остаться только пустая коллекция @allobjects, на самом деле остались названия всех коллекций.

**Comment by ixdu** [comment]
Всё таки желательно читать предыдущие баги:) Почему так работает описано в issue22.
Работа с allobjects абсолютно аналогична работе с другими коллекциями.

**Comment by Databoom** [comment]
1. зашел в Databases
2. нажал Delete all data from database
3. иду в Collections - все коллекции в меню на месте, хотя база пустая. 
4. жму F5 - теперь коллекции ушли.

**Comment by ixdu** [comment]
Хм, а зачем f5, кнопочка обновить у collections не работает? 
Сделано.

**Comment by Databoom** [comment]
Проверил. Вот что вижу. 
1. в пустой базе открыл allobjects, paste туда JSON с 2 коллекциями. 
2. нажал сохранить - вижу, что сохранилось, а в меню не отобразилось. 
![image](https://cloud.githubusercontent.com/assets/13114324/12668730/a2d17e18-c66a-11e5-8a9d-0a4f44ee0374.png)
**То же в обратную сторону: **
3. в полной базе зашел в allobjects, удалил весь JSON
4. нажал сохранить - вижу сообщение, что изменения сохранены, но в меню по-прежнему 2 коллекции. 
![image](https://cloud.githubusercontent.com/assets/13114324/12668769/00942bae-c66b-11e5-9780-b4232fe963b8.png)

**Comment by ixdu** [comment]
сделано
