### ISSUE TITLE
Странное поведение Collection View

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#30]
1. У меня был объект в коллекции tasklist. Я решил передвинуть его в коллекцию HomeList
2. Я вошел в JSON View и поменял принадлежность этого объекта в режиме редактирования руками. 
3. сохранил результат, все отработало нормально. 
4. После этого снова открыл и вижу, что объект не переполз из tasklist в Homelist
5. в tasklist JSON view вижу, что объект стал принадлежать двум коллекциям: tasklist и Homelist. 
6. в Homelist объект тем не менее не отображается.

**Comment by ixdu** [comment]
Опять же это то ли баг то ли фича #22.
Проделал сейчас тоже самое, пунт 6 работает как положено, то есть отображается объект объект в обоих коллекциях.
