### ISSUE TITLE
Если удалить коллекцию, то удаляется не спрашивая

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#32]
Если удалить коллекцию, нажав крестик в меню возле имени коллекции, то удаляется не спрашивая, несмотря на то, что есть объекты принадлежащие данной коллекции

**Comment by ixdu** [comment]
Там всплывает диалог, без нажатия yes в этом диалоге вообще ничего не должно удаляться. Странно, посмотрю.

**Comment by ixdu** [comment]
И всё таки речь точно про меню коллекций, а не про grid. Пока воспроизвести этот баг не удаётся мне.
