### ISSUE TITLE
Надо заполнить подсказку возле Collection URL

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#33]
Надо нам со Славой и с Никитой обсудить и придумать, какие примеры запросов нарисовать.

**Comment by ixdu** [comment]
Если речь про знак вопроса, то неплохо бы сначала смотреть список issues, а потом постить новое: #1 
В целом нужно думать над документацией. Она пока такая очень в стиле manual, tutorial и тд.
Но у любого продукта, используемого разработчиками, должно быть reference на подобии тех что есть в msdn по разным api.
Тогда можно будет в разных подсказках кратко описывать и делать ссылку на конкретный раздел.
