### ISSUE TITLE
После операции над коллекцией приходится снова кликать в базу данных

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#34]
1. открываю коллекцию tasklist
2. открываю JSON view с редактированием
3. редактирую JSON, сохраняю. Все меню схлопывается. 
4. кликаю Collections - тишина. 
5. кликаю databases, потом Collections - тогда открывается.

**Comment by ixdu** [comment]
пока не удаётся мне воспроизвести этот баг ни на хроме ни на фоксе, доберусь до других компьютеров посмотрю

**Comment by ixdu** [comment]
воспроизвёл, правда при других условиях, но думаю это оно. Когда сразу по нужному url с коллекцией загружаешься пункт меню collections закрыт и не открывается. Почему разбираюсь:)

**Comment by ixdu** [comment]
Пару багов с меню залечил, включая тот что описан в предыдущем сообщении. Возможно проблема решена.
