### ISSUE TITLE
при удалении объекта из коллекции, удаляется из всех коллекций

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#35]
Создал объект принадлежащий 2 коллекциям. 
Зашел в table view в одной из коллекций, нажал крестик напротив объекта - удалился без спроса из всех коллекций.

**Comment by ixdu** [comment]
Есть такое, не уверен что получится легко пофиксить, kendo grid работает с базой напрямую, ему лишь предоставляются настройки. Возможно там и можно перехватывать обращения, посмотрим.

**Comment by Databoom** [comment]
Лучше показать диалог, в котором спросить: Удалить из всех коллекций или из конкретной (текущей коллекции)?

**Comment by Databoom** [comment]
Сообщение такое: Delete the object from
- allcollections
- this collection

**Comment by ixdu** [comment]
Ясненько, значит делаем таки полноценный редактор)

**Comment by ixdu** [comment]
Сделано, работает если запрос начинается с коллекции. То есть работает в разделе collections по умолчанию. В разделе queries  работает только если начинается с коллекции, если нет, то используется старое поведение - просто удаление.
