### ISSUE TITLE
Имя коллекции лучше писать в той же панели, что и надписи Grid и JSON

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#36]
Сейчас имя коллекции написано через / возле названия базы данных
Лучше, если оно будет в той же панели, что и надписи Grid и JSON

**Comment by ixdu** [comment]
В эту же панель перенесутся кнопки редактора и ещё куда-то нужно будет делать кнопки загрузки-выгрузки с коллекции.

**Comment by ixdu** [comment]
Сделать можно, но громоздко и не очень логично)

**Comment by ixdu** [comment]
переделано на почти как раньше)
