### ISSUE TITLE
@allobjects в меню сдублировался

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#4]
- В пустой базе открываю @allobjects, перехожу в JSON view, вставляю с помощью copy-paste файл TodoList-simple.json (с исправленной ошибкой). Нажимаю дискету, получаю такой экран (Снимок.PNG) - @allobjects в меню сдублировался. 
![default](https://cloud.githubusercontent.com/assets/13114324/12510208/54cdee6e-c119-11e5-87b9-ef7b45882cf5.PNG)

**Comment by ixdu** [comment]
пофиксил
