### ISSUE TITLE
В разделе Databases надо как-то разделить файлы от базы данных. 

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#42]
Хотя бы чертой отделить, или цветом.

**Comment by ixdu** [comment]
Что сделать?
+ все файловые операции отделить от единственного пункта отчистить 
или
+ заливку файлов в хранилище от остальных трёх пунктов?

**Comment by ixdu** [comment]
Сделал по второму варианту, если нужно переделаю по первому:)
