### ISSUE TITLE
После удаления всех коллекций через левое меню, allobjects все равно отображается непустым

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#45]

**Comment by ixdu** [comment]
есть такое, как оказалось запрос delete не убирает всё из коллекции. Придётся делать ручное корректное удаление.

**Comment by ixdu** [comment]
сделано.

**Comment by Databoom** [comment]
Все равно не уходит.  Теперь 
Остается такой JSON
[
  {
    "id": "0196f8-ea78-4309-a0df-a5ddef63d7",
    "collections": [
      {
        "id": "allobjects"
      }
    ]
  },
  {
    "id": "allobjects"
  }
]

**Comment by ixdu** [comment]
Возможно мусор от предыдущего неудачного удаления или от загрузки из json. Сейчас только что проверил, удалились все коллекции созданные из меню.  Также тот tasklist которые давал, я его загрузил, удалил из меню, всё чисто.

**Comment by Databoom** [comment]
Теперь то же самое проявляется, если очистить базу в разделе Databases, затем кликнуть Collections - показывается непустой allobjects

**Comment by ixdu** [comment]
понятно, это уже проблема базы, доберёмся до неё в процессе. В админке это элегантно не решить)
