### ISSUE TITLE
При добавлении коллекции через allobjects она не отображается в меню

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#46]

**Comment by ixdu** [comment]
Значит добавлено неверно. Логика работы меню основана на логике работы базы, то есть меню просто делает запрос allbojects/collections, это значит что если коллекции нет в меню при обновлении - значит её нет.

Чтобы коллекция существовала нужно чтобы был объект:
{
    "id": "collectionname",
    "collections": [
      {
        "id": "allobjects"
      }
    ]
  }
И  как минимум один объект, принадлежащий этой коллекции.
Возможно тут нужно что-то менять, но это нужно менять в базе и нужно понять не завязано у вас там что-нибудь на это поведение?

**Comment by Databoom** [comment]
там все работает, просто не отображается.

**Comment by ixdu** [comment]
починил, поменял на запрос с фильтрацией на объекты, принадлежащие allobjects.

**Comment by ixdu** [comment]
похоже не починил:(

**Comment by Databoom** [comment]
Вроде работает теперь
