### ISSUE TITLE
При удалении целиком коллекции через JSON view остается пустой объект, который никуда не девается. 

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#48]

**Comment by ixdu** [comment]
Какой именно объект истаётся? Объект в allobjects на подобии такого?:
{
  "id" : "collectioname"
}

Если да, то чего хочется? Чтобы удаление через json было полным? Можно сделать, но ведь логикак в том что показывается там содержимое коллекции. А этот объект есть коллекция, он удаляется крестиком либо из allobjects.
То есть смысл в том, что json режим позволяет редактировать то, что в коллекции. Сама коллекция в самой себе не находится. То есть это явный режим.
Да, можно переделать, если нужно.
Если речь о каком-то другом объекте, то лучше его сюда просто скопипастить)

**Comment by Databoom** [comment]
Остается такая хрень:
[
  {
    "id": "11ba6f-f5e2-43de-91ae-0f221473d8",
    "collections": [
      {
        "id": "tasklist"
      }
    ]
  }
]
Хочется, конечно, чтобы все удалилось бесследно, я же все удалил руками. 
Если это сложно, то можно выдать уведомление, что в этом вью все удалить нельзя, удаляйте через меню

**Comment by ixdu** [comment]
Понятно, нет, такого оставаться не должно, поправлю.

**Comment by ixdu** [comment]
Поправил, удаляет всё содержимое, естественно и коллекция в результате пропадает из меню:)
