### ISSUE TITLE
При перекликивании с @allobjetcs на homelist возникает такое наложение картинок

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#49]
![image](https://cloud.githubusercontent.com/assets/13114324/12644956/9a1a9d1a-c5d7-11e5-8a56-a13e895b32f7.png)

похоже, с allobjects на любую коллекцию - будет то же самое.

**Comment by ixdu** [comment]
Иногда возникало и на обычных коллекциях. Проблема неполного зачищения grid от предыдущего использования.
Сделано.
