### ISSUE TITLE
Косметика. allobjects при клике показывает JSON view, другие коллекции - Grid view

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#50]
Надо бы чтобы одинаково

**Comment by ixdu** [comment]
Так ведь специально сделано в связи с предложение убрать для allobjects grid view. Конечно можно вернуть на место)

**Comment by ixdu** [comment]
А можно убрать переключатель на grid вовсе у allobjects. Сделано так как сейчас потому, что редактировать её удобнее в json режиме, а вот удалять что-нибудь быстрее в grid.

**Comment by Databoom** [comment]
Может быть стоит действительно убрать Grid View у allobjects

**Comment by ixdu** [comment]
убрал выбор режимов. Поживём увидим удобно ли)
