### ISSUE TITLE
Databases: а если в базе уже есть данные, а ты хочешь сделать upload...

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#53]
Databases: а если в базе уже есть данные, а ты хочешь сделать upload. Это значит, ты перезапишешь данные? Тогда надо предупреждение. А если хочешь Append? Может быть сделать отдельную кнопку Append? Возможно стоит обсудить для следующей версии ЛК.

**Comment by ixdu** [comment]
Сейчас это скорее appen. Это как запросы работают в разделе queries. 
То есть новые объекты  заменяют старые объекты с такими же именами. Но если в новых объектах нет каких-то свойств, которые есть в старых, то эти свойства останутся от старых. То есть удаления в нынешней механике нет, только добавление и перезапись таких же объектов.
Если например загрузить новые объекты, то они просто добавятся, так можно добавить коллекцию.
Перезапись же это сначала отчистка, а потом заливка.
Да, тут надо обсуждать что нам нужно. Что понимать например под append? Что понимать под перезаписью? И сделать соответствующее api у базы, потому как сейчас есть только тот механизм что есть. И реализовывать иную механику на клиенте - это как минимум плохой задел)

**Comment by Databoom** [comment]
Это нормальное поведение, главное, правильно отобразить это в документации. 
Это лучше назвать merge. По смыслу больше подходит.
