### ISSUE TITLE
После одной загрузки JSON второй раз этот же файл не загружается.

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#59]
После одной загрузки JSON через {Database: Upload all database data from one JSON file} второй раз этот же файл не загружается. Если гружу другой JSON - то вроде загружается

**Comment by ixdu** [comment]
Да, другой загружался, как выяснилось касяк в компоненте file-upload, не предусмотрена была опция для того, чтобы загружался один и тот же файл.
Сделано
