### ISSUE TITLE
Логин диалог при замене "default" на реальный логин

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#6]
- В приложении VictorTodo-Proto02.html если в строке 75 
            db.login("default", password).done(updateList).fail(showError);
я меняю "default" на реальный логин "varpa@mail.ru" - выскакивает системный логин диалог браузера. 

[VictorTodo-Proto02.rar.txt](https://github.com/Databoom/work/files/100726/VictorTodo-Proto02.rar.txt)

**Comment by ixdu** [comment]
varpa@mail.ru это rootuser, он же host, он же владелец базы, пользователей, групп
varpa@mail.ru это также псевдоним какого-то там tномер, который видно во вкладке account
в db.login используются пользователи, которые содержатся в хосте, то есть те пользователи, которые видны во вкладке access control/users
Вот там есть пользователь default, принадлежащий группе developers.
В общем случае иерархия выглядит так:
rootuser(он же varpa@mail.ru, он же tномеркакой-то) содержит
+ database
+ users
+ groups
