### ISSUE TITLE
Диалог принадлежности коллекции

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#61]
В Grid View, при клике на элемент колонки Collections возникает диалог. Надо поправить: 
"The object belongs to"
Список лучше сделать в виде чекбоксов
Cancel - Change лучше переделать в Cancel - Apply или Apply change
Соответственно, хотя совсем уж не обязательно сделать, чтобы Apply до того как внесены изменения был disabled.

**Comment by ixdu** [comment]
сделано.

**Comment by Databoom** [comment]
Супер!
