### ISSUE TITLE
надпись под username 

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#62]
Надпись под username 
"Only latin, numbers, @ and ." 
как-то не по английски звучит. 
Может быть, чтобы не искать и не морочиться, заменить на регулярное выражение? 
{A:Z, a:z, 0:9, @, .}
Все таки программисты должны знать что это значит.

**Comment by ixdu** [comment]
Да там не в искать было дело, а в краткости. Кратко по английски не описать. 
Ну не знаю, регулярка то получается как минимум вот такая: /^[\w\.\@]+$/
Сделал).

**Comment by Databoom** [comment]
Ну это вообще не читается.
Чем плох мой вариант? Непонятен?

**Comment by ixdu** [comment]
Поставил его)

**Comment by Databoom** [comment]
Что-то не вижу. Это где?

**Comment by Databoom** [comment]
увидел. это возникает только в случае ошибочного ввода. 
может быть сразу показывать? А то раздражает. 
Типа, что ж сразу не сказали?

**Comment by Databoom** [comment]
надпись 
"allowed only ..."
звучит не по-английски
срочно заменить на
"allowed characters: ..."
