### ISSUE TITLE
Databases: надо чтобы иконки не слипались

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#63]
можно чуть раздвинуть строки?

**Comment by ixdu** [comment]
Чуть это относительно, у меня ни на одном браузере они не были слипшимися и у них было достаточно места между друг другом. Сейчас раздвинул ещё, но возможно многовато:)

**Comment by Databoom** [comment]
Пока я вижу только что в Mozilla строки раздвинуты.  В Chrome и MS - слиплось

**Comment by ixdu** [comment]
раздвинул иначе, проверил в хроме, мозилле и эксплорере.
