### ISSUE TITLE
После загрузки базы через Databases: Upload - allobjects показывается пустым

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#65]
После загрузки базы через Upload allobjects показывается пустым
Если кликнуть другие коллекции, то они отображаются правильно, после этого и allobjests отображается правильно

**Comment by ixdu** [comment]
На самом деле и другие неверно отображались. То есть баг работал так: если была выбрана коллекция какая-то, то при переходе в базу данных и обнуление или добавление данных там, а затем возвращение к коллекции редактор не менялся.
Сделано.
