### ISSUE TITLE
upload - download

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#66]
Databases
upload - download: 

При download - без диалога грузится. Может это и нормально. Хотя я бы и здесь уточнил через диалог: ты точно этого хочешь?

При upload возникает диалог. Который я бы переделал. 
1. "Click to upload" выглядит не по-английски. Чтобы не париться, лучше написать "Browse file", или "Select a local file". Поскольку это мы грузим локальный файл. 
2. Кнопка OK - не понятно. Лучше пусть будет кнопка Cancel 
Вообще, везде надо продумать логику. Мне больше нравится, когда кнопки не Yes/No, а OK/Cancel. Обычно так понятнее.

**Comment by ixdu** [comment]
Нет, download не грузится без диалога. А зависит от поведения браузера. В фоксе например появляется диалог сохранить или открыть. Хром сразу молча начинает качать. Получается что мы заставим человека два диалога проходить - свой и браузерный. Можно, если нужно, но по мне так это перебор.

Кнопка Cancel здесь также не логична, что она отменяет? Особенно когда файл загрузился, что человек должен подумать увидев Cancel ?)
Единственная функция данной кнопки это закрыть диалог, уж лучше тогда Close. Поменял по ка на close, но если уж правда надо cancel будет cancel)
Yes, No заменил на Ok и Cancel.

**Comment by Databoom** [comment]
Поскольку из меню кнопки ушли, а на страницу не пришли - то проверить не могу
