### ISSUE TITLE
Кнопка "+" около надписи Databases в левом меню 

### ISSUE THREAD

**Issue by vsalnikov** [Databoom/work#71]
![image](https://cloud.githubusercontent.com/assets/17023659/12975254/4101b0e8-d0cb-11e5-9d4e-314ec9472a11.png)

При нажатии на эту кнопку ничего не происходит.
Нет никакой надписи, которая могла бы пояснить функцию этой кнопки и почему данная функция не доступна пользователю.

**Comment by ixdu** [comment]
Кнопка не активна, api для добавления базы в сервере нет, так что просто убрал кнопку пока)

**Comment by vsalnikov** [comment]
Ок.
