### ISSUE TITLE
Не работает функция "Upload files to storage"

### ISSUE THREAD

**Issue by vsalnikov** [Databoom/work#72]
Выбираю файл и получаю ошибку.
Файл прикладываю.

Перед тестом этой функции выполнял также Cleanup Database

![image](https://cloud.githubusercontent.com/assets/17023659/12976008/d7cd788a-d0d1-11e5-921e-58815d76d8b0.png)

[databoom.txt](https://github.com/Databoom/work/files/126301/databoom.txt)

**Comment by ixdu** [comment]
Cleanup database чистит базу, но не файлы. 
Ошибка починена.

**Comment by vsalnikov** [comment]
Файл вроде бы загрузился.
Но я не могу закрыть данный тикет, так как нет способа проверить, загружен файл или нет!

Должна быть возможность каким-либо образом увидеть файл в базе.
Сейчас я не вижу способа, как этот загруженный файл получить обратно из базы и как просмотреть список файлов, загруженных в базу.

Возможно надо читать документацию к базе?

**Comment by ixdu** [comment]
Да, в доках есть об этом. Однако в целом работа с файлами толком просто не сделана. Нет ни возможность запросить список файлов, ни удалить и тд и тп. Ниже по этому поводу есть уже тикет #26, нет смысла держать два тикета по одной и той же теме недостачных возможностей работы с файлами.
В рамках этого же тикета максимум что можно сделать это сообщение, с адресом файла в ответ. Думаю имеет смысл, но сообщение прочитал и всё, забыл где он, то есть всё равно недостаточно.

**Comment by vsalnikov** [comment]
Сообщение со ссылкой на файл это будет хорошо!
Ссылку можно сохранить где-нибудь. Все-таки это хоть какой-то результат.

**Comment by ixdu** [comment]
Добавил отображение ссылки на загружунный файл.

**Comment by vsalnikov** [comment]
Ok.
