### ISSUE TITLE
Раздел Queries - работа с коллекцией, которая не существует в базе 

### ISSUE THREAD

**Issue by vsalnikov** [Databoom/work#73]
Если в разделе Queries в поле "query string" написать строку, которая не является коллекцией, и вообще ничем не является, например "dfdfdf", то ничего не происходит.
Ожидаемое поведение - надпись, поясняющая, что "dfdfdf" не является именем коллекции или каким-либо словом языка запросов.

**Comment by ixdu** [comment]
Увы, но на данный момент способа определить точно почему нет результатов не существует. 
Сейчас это работает так: пишем строку запросов, она отсылается базе и в ответ приходит либо массив данных либо пустой массив. То есть нет разницы некорректный или корректный запрос. В ответ или будут данные найдены или не будут.
Посему сделал так: когда ответ на запрос ничего не содержит - всплывает соообщение о том что нет ничего по этому запросу.

**Comment by vsalnikov** [comment]
Долго искал глазами на экране это сообщение.
Оно оказалось внизу экрана.

Вот картинка, где видно, что сообщение слишком маленькое и незаметное.

![image](https://cloud.githubusercontent.com/assets/17023659/13046703/7484781a-d3eb-11e5-946c-240a3c8a6de0.png)

Предлагаю разместить его в районе строки запроса. Это будет понятнее.

Тикет пока не закрываю.

**Comment by Databoom** [comment]
Мне кажется, поведение приемлемое, учитывая, что таблица при этом пустая. 
И, исходя из логики задач прототипирования, у нас многое сделано так. 
Либо ты получаешь результат, либо пустое множество. 
Разве не так?

**Comment by ixdu** [comment]
Попроавил, всплывает теперь в районе строки запроса.

**Comment by vsalnikov** [comment]
Сообщение теперь вслывает на видном месте.
Заметил, что иногда оно не всплывает.
Ситуацию, когда сообщение не всплывает, можно воспроизвести следующим образом:
1) Открыть (или обновить страницу) в разделе Queries
2) Быстро ввести текст "вававава" в поле запроса (любой текст кириллицей)
Результат: сообщение не всплывает

Если затем ввести что-то латиницей, то сообщение всплывает.

**Comment by vsalnikov** [comment]
Этот баг пока не пофиксен.

**Comment by ixdu** [comment]
поправил.

**Comment by ixdu** [comment]
странно, баг не только пофикшен, но и переделана теперь логика, живого поиска нет теперь.
