### ISSUE TITLE
Раздел Queries - кнопка удаления нового объекта не должна работать

### ISSUE THREAD

**Issue by vsalnikov** [Databoom/work#74]
При создании новой строки в таблице в разделе Queries, кнопка удаления работает, даже когда объект еще не создан.
Если добавить строку в таблицу, и,  не заполнив поля, нажать кнопку удаления, то функция удаления не работает.
Ожидаемое поведение: кнопка удаления отсутствует для новых строк.

![image](https://cloud.githubusercontent.com/assets/17023659/12976274/f5c820ae-d0d3-11e5-9277-4eb4f3320f90.png)

**Comment by ixdu** [comment]
сделано.

**Comment by vsalnikov** [comment]
Кнопка удаления пропала. Ок.
