### ISSUE TITLE
Раздел Queries - сортировка таблицы по колонке "collections" работает некорректно

### ISSUE THREAD

**Issue by vsalnikov** [Databoom/work#75]
Открыть раздел Queries, ввести имя коллекции.
Нажать несколько раз на заголовок колонки "collections"
При нажатии на заголовок колонки  "collections" содержимое таблицы пропадает.
Если нажать еще 1-2 раза, то содержимое таблицы опять появляется.

**Comment by ixdu** [comment]
Отключил сортировку для collections и других колонок, содержащих массивы объектов. База не умеет отрабатывать order by по таким полям. Это правда не решение бага как такового, а его переквалификация в баг базы:)

**Comment by ixdu** [comment]
Сортировка по полям с массивами ссылок(которым является объект collections) пока не поддерживается. И ещё надо будет определить как именно она должна работать. Баг закрываю потому как это и не баг, а такого и не планировалось. Но в новых версиях базы возможно будет подобное работать, как будет, добавим поддержку и в грид.
