### ISSUE TITLE
Нет возможности создать новые колонки при редактировании коллекции (не считая варианта через json)

### ISSUE THREAD

**Issue by vsalnikov** [Databoom/work#76]
При редактировании коллекции, если это новая коллекция, то я не могу ввести никакие данные, кроме ID элементов.

**Comment by ixdu** [comment]
Сделано, правда кнопочки не красивые, найду подходящие иконки заменю)

**Comment by vsalnikov** [comment]
Кнопки вроде нормальные. Ок.
