### ISSUE TITLE
Форма редактирования JSON: в режиме readonly текст серый и трудно читать

### ISSUE THREAD

**Issue by vsalnikov** [Databoom/work#77]
Форма редактирования JSON: в режиме readonly текст серый и трудно читать

![image](https://cloud.githubusercontent.com/assets/17023659/12976484/7d609da6-d0d5-11e5-89f0-c26febcd9441.png)

**Comment by ixdu** [comment]
Заменил прозрачность на затенение, читается лучше.

**Comment by vsalnikov** [comment]
Стало лучше!
