### ISSUE TITLE
Появление странной таблицы с содержимым коллекции в режиме readonly под таблицей редактирования коллекции

### ISSUE THREAD

**Issue by vsalnikov** [Databoom/work#78]
Перейти в режим редактирования коллекции.
Будет показана таблица, позволяющая редактировать коллекцию.
В первой строке таблицы кликнуть в колонке collections.
Будет показан диалог выбора коллекции.
Нажать Cancel.
Снизу появится еще одна таблица, где показывается содержимое коллекции на сером фоне (типа readonly).
Ожидаемое поведение: не показывается ничего нового.

**Comment by ixdu** [comment]
Не, то не ридонли, то многократное наложение при отрисовке:)
Исправлено.

**Comment by vsalnikov** [comment]
Проблема исчезла.
