### ISSUE TITLE
Странная неработающая кнопка в меню проектов

### ISSUE THREAD

**Issue by vsalnikov** [Databoom/work#79]
Ожидаемое поведение: при нажатии на эту кнопку скачивается что-то, так как кнопка имеет соответствующую иконку.
Если это не кнопка, а просто иконка, то не понятно её назначение.

![image](https://cloud.githubusercontent.com/assets/17023659/12976685/01548fc2-d0d7-11e5-9671-275cc4205e29.png)

**Comment by ixdu** [comment]
Аккаунт из-под которого была обнаружена эта ошибка был создан на старом сайте через getdatabase? или на этом через signup? Если через getdatabase то так быть и должно, по сути для старых аккаунтов весь раздел projects не работает, файлы не созданы. Надо будет подумать то ли не отображать то ли создавать по иначе.
Если же через новый сайт и signup, то какой браузер?

**Comment by vsalnikov** [comment]
Аккаунт создавал новый сегодня на databoom.space, нажав signup
Браузер - Chrome
После того кликания на иконки скачивания, браузер, через некоторое время, выдал запрос на подтверждения скачивания нескольких файлов и затем что-то загрузилось.

**Comment by ixdu** [comment]
Хоть и вчера, но на старом сайте через старый механизм, а не через signup.html. Там попросту нет  реализации projects. Поэтому теперь аккаунты разделяются по версии и для старых акканутов не будут показываться те возможности, которые в них недоступны. В данном случае это projects.
Чтобы раздел projects был доступен, нужно будет зарегистрироваться через signup.html там же где admin.html:) Может быть в дальнейшем подумаем над автоконвертом всех аккаунтов.
