### ISSUE TITLE
Users list не показывает текущего User-a

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#82]
Лучше надпись такую: 
Selegt group(s) for the user <имя пользователя>

![image](https://cloud.githubusercontent.com/assets/13114324/13042380/ca96e118-d3d0-11e5-9faf-4a003cc5a24e.png)

**Comment by ixdu** [comment]
сделано

**Comment by Databoom** [comment]
я, правда, угловые скобки использовал чтобы обозначить служебную часть текста, но и так ничего. 
Может быть лучше квадратные скобки использовать? Смотрятся лучше в таком контексте. Или можно вообще без них.

**Comment by ixdu** [comment]
Лучше наверное тогда совсем без скобок
