### ISSUE TITLE
не меняется grid в queries

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#83]
1. захожу в Queries
2. ввожу запрос 
homelist?$filter=contains(text, 'set')
отображается результат
3. стираю запрос - результат не меняется, хотя запроса уже нет. Дальше - что ни делаю - не меняется. 

![image](https://cloud.githubusercontent.com/assets/13114324/13042628/b6bddf5a-d3d2-11e5-9e22-432c469bdf4b.png)

**Comment by ixdu** [comment]
поправил.

**Comment by Databoom** [comment]
Работает частично. 
1. Если удалить запрос - остается как было. 
2. Если нажать Refresh - остается как было. 
3. Если нажать F5 - то очищается.

**Comment by ixdu** [comment]
поправил.
