### ISSUE TITLE
Нужно ли в Queries add row и add column? 

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#84]
Для этого раздела мы должны только отображать результат, а все изменения делаются через Query, если надо. Я не прав? 

Тем более, что не работает. 
После ввода такой информации, удаление не работает. 
![image](https://cloud.githubusercontent.com/assets/13114324/13042697/40670394-d3d3-11e5-9879-b9a33573059f.png)

**Comment by ixdu** [comment]
Верно, даже если бы работало удаление по логике добавление столбцов или полей не должно позволяться, потому как результатом запроса может быть не только объекты из какой-то одной коллекции, а любой набор объектов. 
Убрал кнопки в queries.
