### ISSUE TITLE
На некоторых размерах экрана плывет граница столбца в гриде редактирования коллекции

### ISSUE THREAD

**Issue by vsalnikov** [Databoom/work#85]
На некоторых размерах экрана плывет граница столбца в гриде редактирования коллекции.
В Хроме, при масштабе 100% и разрешении экрана 1920 на 1080, этот эффект наблюдается.

![image](https://cloud.githubusercontent.com/assets/17023659/13045849/b6ce18e8-d3e6-11e5-8227-61cedb43aa18.png)

Вот мы видим, что граница заголовка таблицы не соответствует границе столбца таблицы.
Если можно это исправить, то стоит исправить.

Такая проблема бывает и у других (на других сайтах).
Если исправить трудно, то, думаю, стоит пока оставить так.

**Comment by ixdu** [comment]
Подтверждаю, данная проблема возникает переодически возникает. Возможно решаема, если удастся найти о ней упоминание и какой-нибудь хак пофиксю легко. В противном случае придётся перерывать редактор, сомневаюсь что это быстро будет:)

**Comment by vsalnikov** [comment]
Пофиксено.
