### ISSUE TITLE
При добавлении строки в коллекцию не заполнена колонка "collections".

### ISSUE THREAD

**Issue by vsalnikov** [Databoom/work#86]
При добавлении строки в коллекцию не заполнена колонка "collections".

![image](https://cloud.githubusercontent.com/assets/17023659/13046913/9eb68b9a-d3ec-11e5-8eb2-eddeec37ecd2.png)

Ожидаемое поведение: при добавлении строки в коллекцию Cars, колонка collections, содержит текст "Cars".

Фактическое поведение: Нажимаю New Row. Вижу новую строку, где не заполнена колонка collections. Заполняю любое поле. Строка обновляется и тут я понимаю, что, хотя колонка collections была пуста, строка была добавлена именно в коллекцию Cars, а не куда-то еще.

**Comment by ixdu** [comment]
Тут дело в том, что запись при добавлении существует только в редакторе, но не в базе. Изменил логику, теперь добавляется сразу с заполненным полем collections и с присвоенным id.

**Comment by vsalnikov** [comment]
Теперь такая ситуация: когда нажимаешь в таблице на ячейку выбора коллекции, открывается диалог выбора коллекции, при этом ячейка очищается и показывается пустой. Такое поведение не понятно. Почему ячейка должна очищаться во время редактирования?

![image](https://cloud.githubusercontent.com/assets/17023659/13139625/846df26a-d63e-11e5-975f-ab26e2c79fde.png)

Баг пока не закрываю :)

**Comment by ixdu** [comment]
У используемого нами kendo grid есть предопределённое поведение, согласно которому при редактировании появляется контрол. Поскольку у нас диалог, то вместо контрола пустота. Способа обхода этого я пока не нашёл, найду - пофиксю. Может он и на поверхности лежит)

**Comment by vsalnikov** [comment]
Этот баг пока не пофиксен.
