### ISSUE TITLE
Возник загадочный объект

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#87]
Каким-то образом (я не заметил как) возник объект
{
    "id": "фыва",
    "text": "фыва"
  },
Который ни коллекция, ни принадлежит никакой коллекции. 
Возможно, я его создал, но как это произошло - воспроизвести не смог. 
![image](https://cloud.githubusercontent.com/assets/13114324/13053006/356812a4-d413-11e5-9e79-e84df5ab1dae.png)

**Comment by ixdu** [comment]
Коллекции это же астракция, это всего лишь свойство, содержащее массив ссылок на объекты. По прежнему можно создавать просто объекты. Такой объект мог быть создан в грид режиме, если вместо id написать фыва и вместо text тоже. Сейчас уже нельзя, потому что грид теперь при добавлении строчки создаёт объект сначала, а потом даёт его редактировать. Но ещё вчера можно было.
