### ISSUE TITLE
Когда выгружаешь allobjects в JSON возникают паразитные объекты

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#89]
Вот такие
 {
    "id": "0196f8-ea78-4309-a0df-a5ddef63d7",
    "collections": [ { "id": "allobjects" } ]
  },
  { "id": "allobjects" },

**Comment by ixdu** [comment]
Уже не возникают, баг был, когда сохраняешь allobjects через json редактор то ничейные объекты становятся принадлежащими коллекции allobjects.
