### ISSUE TITLE
Ширина колонок при загрузке грида

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#90]
можно было бы при загрузке ширину колонок, если значения уже, чем заголовки, сделать по ширине заголовков. 
Потом можно самому сдвигать - раздвигать, но каждый раз делать узкие колонки своими руками утомляет.

**Comment by ixdu** [comment]
Сделал ширину колонок по ширине заголовка. По ширине содержимого сделать не выйдет, у нас виртуальный скроллинг, содержимое заранее неизвестно.
