### ISSUE TITLE
Логотип databoom вверху слева должен быть гиперссылкой

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#92]
Сейчас это не так для СР

**Comment by ixdu** [comment]
Оно было так, Наиль просил вообще убрать все ссылки на home, значит верну на место.
Единственное возражение - на малых разрешениях в работе иногда промахиваешься и тыкаешь на этот логотип. Происходит потому, что на малых разрешениях меню схлопывается и становится выдвижным. Но с другой стороны, кто будет использовать админку в режиме полэкрана)

**Comment by Databoom** [comment]
То что написал Наиль надо с осторожностью реализовывать.
Я просил только баги зачищать. А остальное надо обсуждать.

**Comment by ixdu** [comment]
Поправил.
