### ISSUE TITLE
Загрузка файлов. Надпись "Drop files Here". Почему files? Оно принимает только 1 файл. Если класть несколько, то берет только 1.

### ISSUE THREAD

**Issue by vsalnikov** [Databoom/work#93]
Загрузка файлов. Надпись "Drop files Here". Почему files? Оно принимает только 1 файл. Если класть несколько, то берет только 1.

Я плохо знаю английский, возможно это нормально написано?
Может все-таки написать "Drop file here" ?

![image](https://cloud.githubusercontent.com/assets/17023659/13139845/94a73ca8-d63f-11e5-8293-e89ead15d7f0.png)

**Comment by ixdu** [comment]
Нет, не нормально, оказалось file-upload просто не меняет надпись. Поправил.

**Comment by vsalnikov** [comment]
Ok
