### ISSUE TITLE
Кнопка "Logout". Догадаться, что это она, можно только, если навести мышь и прочитать её tooltip

### ISSUE THREAD

**Issue by vsalnikov** [Databoom/work#94]
Кнопка "Logout" - догадаться, что это она, можно только, если навести мышь и прочитать её tooltip

![image](https://cloud.githubusercontent.com/assets/17023659/13139914/0e3aa014-d640-11e5-9c82-55a51c638d1e.png)

Хотел проверить работает ли выход из личного кабинета, секунд 15 искал кнопку "Выхода".

**Comment by ixdu** [comment]
Согласен, материал иконки придуманы инопланетянами, по мне кроме домика они все непонятны. Нужно подумать чем заменить.

**Comment by Databoom** [comment]
Погуглил "logout icon". Вот такие есть варианты. 
Пометил те, которые мне лично нравятся. 
![image](https://cloud.githubusercontent.com/assets/13114324/14058631/ce9582ca-f337-11e5-82bc-ddd71b1b780e.png)

**Comment by ixdu** [comment]
Поменял на почти как второй вариант.
