### ISSUE TITLE
Раздел Access Control. При выборе группы в строке пользователя - не показывается текущая его группа.

### ISSUE THREAD

**Issue by vsalnikov** [Databoom/work#95]
Раздел Access Control. При выборе группы в строке пользователя - не показывается текущая его группа.

![image](https://cloud.githubusercontent.com/assets/17023659/13139974/6bf40bb4-d640-11e5-9b69-5e826e073589.png)

**Comment by ixdu** [comment]
Теперь показывается.

**Comment by vsalnikov** [comment]
Пофиксено.
