### ISSUE TITLE
После удаления пользователей в разделе Access Control - список пользователей перестал работать, что-то в нем поломалось

### ISSUE THREAD

**Issue by vsalnikov** [Databoom/work#98]
После удаления пользователей в разделе Access Control - список пользователей перестал работать, что-то в нем поломалось.

**Comment by ixdu** [comment]
Однажды такой баг встретил, но найти не сумел. Как перестал работать? Как сейчас выглядит, скрин было бы замечательно. И имя пользователя, то login, посмотрю что в базе происходит.

**Comment by vsalnikov** [comment]
Пока не разобрался как воспроизвести. Под моим именем пользователя там все поломано, кажется.
t249

**Comment by ixdu** [comment]
ну там остаётся возможность добавлять пользователей, просто получается так что удаление происходит некорректно и вместо пользователей записывают только фрагменты. Да, это тот самый баг, найдне значит пофиксим)

**Comment by ixdu** [comment]
Пользователей починил, баг найти оказалось сложнее)

**Comment by ixdu** [comment]
Добавил проверок при добавлении пользователя. Теперь пока не введены все его поля он не сохраняется(так и должно быть, потому что пользователь не может быть сохранён всего с несколькими полями). Также его теперь нельзя удалить, пока не создан(опять же нельзя удалять то, чего нет).
Пока будем считать проблему решённой, но если вдруг она проявится в каком-то другом случае баг переоткроем.

**Comment by vsalnikov** [comment]
Пользователи удаляются, добавляются. вроде ничего не ломается. Ок.
