### ISSUE TITLE
Под мозиллой черные буквы

### ISSUE THREAD

**Issue by Databoom** [Databoom/work#99]
![image](https://cloud.githubusercontent.com/assets/13114324/13195976/edb12230-d7d1-11e5-85e3-950583d36110.png)

![image](https://cloud.githubusercontent.com/assets/13114324/13195978/fd5a01e8-d7d1-11e5-9d15-e7cd3b82ebb3.png)

**Comment by ixdu** [comment]
В целом была проблема с импортом стилей под мозиллой, не только стилем диалогов.
Поправил.
